import type { BlogPost } from './posts';

/** SEO posts targeting airport long-tail keywords — linked from airport landing pages. */
export const airportBlogPosts: BlogPost[] = [
  {
    postId: 'airport-mad-es',
    slug: 'traslado-compartido-madrid-barajas',
    locale: 'es',
    title: 'Cómo compartir taxi al aeropuerto de Madrid-Barajas con tu mismo vuelo',
    summary:
      'Guía práctica para coordinar un traslado compartido a MAD con personas con planes compatibles del mismo vuelo usando Cojauny.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Traslado compartido al aeropuerto de Madrid',
    heroWidth: 1280,
    heroHeight: 720,
    body: ["Cojauny prepara una beta para conectar a personas con planes de vuelo compatibles. Esta guía ofrece consejos de organización; no acredita funciones disponibles, operadores asociados ni resultados de ahorro.", "Comprueba fecha, terminal, hora y destino. Dos personas con el mismo vuelo pueden necesitar rutas diferentes, llevar distinto equipaje o salir a horas distintas. Acuerda una hora límite de espera y un punto de encuentro público y permitido.", "Consulta las condiciones del aeropuerto y del operador autorizado. Confirma plazas, espacio de equipaje, accesibilidad y precio total antes de reservar. Si faltan datos, conserva una alternativa independiente. No publiques documentos, tarjetas de embarque ni datos bancarios en el grupo.", "Un correo confirmado no demuestra la identidad de alguien ni garantiza su comportamiento. La eliminación de un chat tampoco borra capturas o copias ajenas. Consulta las políticas del servicio que utilices y comparte solo lo necesario.", "[Apúntate a la lista de espera](/es#beta). El registro no garantiza una invitación, cobertura en un aeropuerto concreto ni una fecha de lanzamiento."],
    tags: ['madrid', 'mad', 'traslado aeropuerto', 'carpool'],
    categories: ['aeropuertos'],
    publishedAt: '2026-06-30T10:00:00.000Z',
    updatedAt: '2026-06-30T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 4,
  },
  {
    postId: 'airport-lhr-en',
    slug: 'shared-transfer-london-heathrow',
    locale: 'en',
    title: 'How to share a ride to London Heathrow with passengers on your flight',
    summary:
      'A practical guide to coordinating a shared LHR transfer with people with compatible plans on the same flight using Cojauny.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Shared transfer to London Heathrow',
    heroWidth: 1280,
    heroHeight: 720,
    body: ["Cojauny is preparing a beta to connect people with compatible flight plans. This guide offers practical advice; it does not establish available features, transport partnerships or measured savings.", "Check date, terminal, timing and destination. People on the same flight may need different routes, carry different luggage or leave at different times. Agree on a waiting deadline and a public, permitted meeting point.", "Check the airport rules and licensed operator’s conditions. Confirm seats, luggage space, accessibility and total price before booking. Keep an independent backup when details remain uncertain. Do not publish identity documents, boarding passes or bank details in the group.", "A confirmed email does not establish someone’s identity or guarantee their behaviour. Deleting a chat does not erase other people’s screenshots or copies. Check the service’s policies and share only what coordination requires.", "[Join the beta waitlist](/#beta). Registration does not guarantee an invitation, coverage at a particular airport or a launch date."],
    tags: ['london', 'lhr', 'heathrow', 'airport transfer'],
    categories: ['airports'],
    publishedAt: '2026-06-30T10:00:00.000Z',
    updatedAt: '2026-06-30T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 4,
  },
  {
    postId: 'airport-fra-de',
    slug: 'geteilter-transfer-frankfurt',
    locale: 'de',
    title: 'Geteilter Transfer zum Flughafen Frankfurt mit Passagieren deines Flugs',
    summary:
      'Praxisleitfaden für einen geteilten FRA-Transfer mit Menschen mit passenden Reiseplänen auf dem gleichen Flug mit Cojauny.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Geteilter Transfer nach Frankfurt',
    heroWidth: 1280,
    heroHeight: 720,
    body: ["Cojauny bereitet eine Beta vor, die Menschen mit passenden Flugplänen verbinden soll. Dieser Leitfaden bietet praktische Hinweise; er belegt keine verfügbaren Funktionen, Kooperationen oder gemessenen Einsparungen.", "Prüfe Datum, Terminal, Uhrzeit und Ziel. Menschen auf demselben Flug können verschiedene Ziele, Gepäckmengen oder Abfahrtszeiten haben. Vereinbart eine Wartefrist und einen öffentlichen, erlaubten Treffpunkt.", "Prüfe Flughafenregeln und Bedingungen des zugelassenen Anbieters. Kläre Sitzplätze, Gepäckraum, Barrierefreiheit und Gesamtpreis vor der Buchung. Halte eine unabhängige Alternative bereit. Veröffentliche keine Ausweise, Bordkarten oder Bankdaten in der Gruppe.", "Eine bestätigte E-Mail-Adresse ist kein Identitätsnachweis und garantiert kein Verhalten. Gelöschte Chats entfernen keine fremden Screenshots oder Kopien. Prüfe die Regeln des Dienstes und teile nur nötige Daten.", "[Trag dich in die Beta-Warteliste ein](/de#beta). Die Anmeldung garantiert weder eine Einladung noch einen bestimmten Flughafen oder Starttermin."],
    tags: ['frankfurt', 'fra', 'flughafentransfer'],
    categories: ['flughäfen'],
    publishedAt: '2026-06-30T10:00:00.000Z',
    updatedAt: '2026-06-30T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 3,
  },
  {
    postId: 'airport-cdg-fr',
    slug: 'transfert-partage-paris-cdg',
    locale: 'fr',
    title: 'Comment partager un transfert vers Paris CDG avec des passagers de votre vol',
    summary:
      'Guide pratique pour coordonner un transfert partagé vers CDG avec des personnes ayant des projets compatibles sur le même vol via Cojauny.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Transfert partagé vers Paris CDG',
    heroWidth: 1280,
    heroHeight: 720,
    body: ["Cojauny prépare une bêta pour relier des personnes ayant des projets de vol compatibles. Ce guide donne des conseils pratiques ; il ne prouve pas la disponibilité de fonctions, partenariats ou économies mesurées.", "Vérifiez date, terminal, horaire et destination. Des personnes sur le même vol peuvent avoir des trajets, bagages et heures de départ différents. Fixez une limite d’attente et un rendez-vous public et autorisé.", "Consultez les règles de l’aéroport et du transporteur autorisé. Confirmez places, bagages, accessibilité et prix total avant de réserver. Gardez une alternative indépendante. Ne publiez ni documents d’identité, ni cartes d’embarquement, ni données bancaires dans le groupe.", "Un e-mail confirmé ne prouve pas l’identité et ne garantit pas le comportement. Supprimer un chat n’efface pas les captures ou copies des autres. Consultez les règles du service et partagez seulement le nécessaire.", "[Inscrivez-vous sur la liste d’attente](/fr#beta). L’inscription ne garantit ni invitation, ni disponibilité dans un aéroport précis, ni date de lancement."],
    tags: ['paris', 'cdg', 'transfert aéroport'],
    categories: ['aéroports'],
    publishedAt: '2026-06-30T10:00:00.000Z',
    updatedAt: '2026-06-30T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 3,
  },
];
