import type { BlogPost } from './posts';

/** SEO posts targeting airport long-tail keywords — linked from airport landing pages. */
export const airportBlogPosts: BlogPost[] = [
  {
    postId: 'airport-mad-es',
    slug: 'traslado-compartido-madrid-barajas',
    locale: 'es',
    title: 'Cómo compartir taxi al aeropuerto de Madrid-Barajas con tu mismo vuelo',
    summary:
      'Guía práctica para coordinar un traslado compartido a MAD con pasajeros verificados del mismo vuelo usando Cojauny.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Traslado compartido al aeropuerto de Madrid',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Traslado compartido a Madrid-Barajas (MAD)',
      'Compartir transporte al aeropuerto con personas de tu mismo vuelo reduce costes y aumenta la confianza. Con Cojauny introduces tu vuelo, revisas perfiles verificados y coordinas el punto de encuentro en chat.',
      '## Ventajas frente a un taxi solo',
      '- Ahorro medio del 50-75% en el tramo ciudad-aeropuerto\n- Perfiles con documento y valoraciones visibles\n- Coordinación por número de vuelo, no por suerte',
      '[Reserva tu plaza beta en Cojauny](/es#beta)',
    ],
    tags: ['madrid', 'mad', 'traslado aeropuerto', 'carpool'],
    categories: ['aeropuertos'],
    publishedAt: '2026-06-30T10:00:00.000Z',
    updatedAt: '2026-06-30T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 4,
  },
  {
    postId: 'airport-lhr-en',
    slug: 'shared-transfer-london-heathrow',
    locale: 'en',
    title: 'How to share a ride to London Heathrow with passengers on your flight',
    summary:
      'A practical guide to coordinating a shared LHR transfer with verified passengers on the same flight using Cojauny.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Shared transfer to London Heathrow',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Shared transfer to London Heathrow (LHR)',
      'Sharing airport transport with people on your exact flight cuts costs and builds trust. Enter your flight on Cojauny, review verified profiles, and coordinate pickup in secure chat.',
      '## Why not ride alone?',
      '- Average 50-75% savings vs solo taxi\n- ID-verified profiles and visible ratings\n- Flight-number matching, not random carpool luck',
      '[Reserve your beta spot](/en#beta)',
    ],
    tags: ['london', 'lhr', 'heathrow', 'airport transfer'],
    categories: ['airports'],
    publishedAt: '2026-06-30T10:00:00.000Z',
    updatedAt: '2026-06-30T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 4,
  },
  {
    postId: 'airport-fra-de',
    slug: 'geteilter-transfer-frankfurt',
    locale: 'de',
    title: 'Geteilter Transfer zum Flughafen Frankfurt mit Passagieren deines Flugs',
    summary:
      'Praxisleitfaden für einen geteilten FRA-Transfer mit verifizierten Passagieren auf dem gleichen Flug mit Cojauny.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Geteilter Transfer nach Frankfurt',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Geteilter Transfer nach Frankfurt (FRA)',
      'Transport zum Flughafen mit Menschen auf deinem Flug spart Kosten und schafft Vertrauen. Gib deinen Flug in Cojauny ein, prüfe verifizierte Profile und koordiniere den Treffpunkt im Chat.',
      '[Beta-Platz reservieren](/de#beta)',
    ],
    tags: ['frankfurt', 'fra', 'flughafentransfer'],
    categories: ['flughäfen'],
    publishedAt: '2026-06-30T10:00:00.000Z',
    updatedAt: '2026-06-30T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 3,
  },
  {
    postId: 'airport-cdg-fr',
    slug: 'transfert-partage-paris-cdg',
    locale: 'fr',
    title: 'Comment partager un transfert vers Paris CDG avec des passagers de votre vol',
    summary:
      'Guide pratique pour coordonner un transfert partagé vers CDG avec des passagers vérifiés sur le même vol via Cojauny.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Transfert partagé vers Paris CDG',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Transfert partagé vers Paris Charles de Gaulle (CDG)',
      'Partager le transport vers l\'aéroport avec des personnes sur votre vol réduit les coûts et renforce la confiance. Saisissez votre vol sur Cojauny, consultez les profils vérifiés et coordonnez le rendez-vous en chat.',
      '[Réserver une place bêta](/fr#beta)',
    ],
    tags: ['paris', 'cdg', 'transfert aéroport'],
    categories: ['aéroports'],
    publishedAt: '2026-06-30T10:00:00.000Z',
    updatedAt: '2026-06-30T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 3,
  },
];
