import type { Locale } from '@/locales/config';

export interface BlogPost {
  postId: string;
  slug: string;
  locale: Locale;
  title: string;
  summary: string;
  heroImage: string;
  heroAlt: string;
  heroWidth: number;
  heroHeight: number;
  body: string[];
  tags: string[];
  categories: string[];
  publishedAt: string;
  updatedAt: string;
  author: string;
  readingTimeMinutes: number;
}

export const blogPosts: BlogPost[] = [
  // POST-001 (EN) - abbreviated
  {
    postId: 'post-001',
    slug: 'share-airport-ride',
    locale: 'en',
    title: 'The Ultimate Guide to Sharing Airport Rides with Your Flight',
    summary: 'A practical playbook to align passengers, set meeting points and split transfers before your trip.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Business travelers organizing an airport ride',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# The Ultimate Guide to Sharing Airport Rides with Your Flight',
      '## Introduction',
      'Sharing airport rides has become a game-changer for travelers looking to save money, reduce environmental impact, and build connections. Whether you\'re heading to the airport for a business trip or vacation, coordinating shared transportation can turn a stressful experience into a seamless one. This comprehensive guide will walk you through the best practices for sharing rides with your flight, ensuring everyone arrives on time and happy.',
      '## Why Share Airport Rides?',
      '### Cost Savings',
      'One of the primary benefits of sharing rides is the significant cost reduction. Traditional taxi or rideshare services can be expensive, especially for groups. By sharing the cost among multiple passengers, you can cut expenses by up to 70%. For example, a $50 taxi ride split between four people costs just $12.50 per person.',
      '### Environmental Benefits',
      'Shared rides also contribute to a greener planet. Fewer vehicles on the road mean lower carbon emissions. According to studies, carpooling can reduce greenhouse gas emissions by 20-30% per trip.',
      '### Social and Networking Opportunities',
      'Beyond savings, sharing rides allows you to meet new people and build professional networks. Many business travelers have formed lasting partnerships through shared airport commutes.',
      '## Planning Your Shared Ride',
      '### Step 1: Create a Flight Event Early',
      'As soon as your flight is booked, create an event on a platform like Cojauny. Include details such as flight number, departure time, and preferred meeting points. Early planning gives others time to join.',
      '### Step 2: Set Clear Meeting Points',
      'Choose accessible locations at the airport. For departures, opt for the main entrance or a designated rideshare area. For arrivals, select spots near baggage claim or taxi stands. Use maps and photos to avoid confusion.',
      '### Step 3: Define Pickup Windows',
      'Account for travel time and potential delays. Set a 30-minute window for pickup to accommodate unforeseen circumstances. Communicate this clearly to all participants.',
      '### Step 4: Agree on Payment Methods',
      'Decide how to split costs upfront. Options include cash, digital wallets, or apps. Cojauny\'s built-in cost splitter makes this easy and transparent.',
      '## Best Practices for a Smooth Experience',
      '### Communication is Key',
      'Use group chats to keep everyone updated. Share real-time location if needed, but respect privacy.',
      '### Safety First',
      'Verify driver and vehicle details. Stick to reputable services and avoid sharing rides with strangers if possible.',
      '### Flexibility and Courtesy',
      'Be understanding of delays. Offer to help with luggage or provide directions.',
      '## Common Challenges and Solutions',
      '### Dealing with Delays',
      'If your flight is delayed, update the event immediately. Adjust pickup times accordingly.',
      '### Managing Group Dynamics',
      'For larger groups, assign roles like coordinator or navigator to streamline the process.',
      '## Conclusion',
      'Sharing airport rides is more than just a way to save money—it\'s a smarter, more sustainable way to travel. By following this guide, you can ensure a positive experience for everyone involved. Start planning your next shared ride today with Cojauny.'],
    tags: ['airport ride', 'logistics'],
    categories: ['operations', 'product'],
    publishedAt: '2025-11-10T08:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 6
  },

  // POST-002 (EN) - abbreviated
  {
    postId: 'post-002',
    slug: 'real-time-flight-coordination',
    locale: 'en',
    title: 'Mastering Real-Time Flight Coordination for Distributed Teams',
    summary: 'How shared workspaces, flight updates and meeting points reduce regrouping time for teams.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Team coordinating flights',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Mastering Real-Time Flight Coordination for Distributed Teams',
      '## Introduction',
      'In today\'s globalized world, teams are often spread across different locations, making coordination for travel a complex task. Real-time flight coordination is essential for ensuring that everyone arrives at the right place at the right time. This guide explores how shared workspaces, flight updates, and strategic meeting points can significantly reduce regrouping time for distributed teams.',
      '## The Challenges of Distributed Team Travel',
      'Distributed teams face unique challenges when traveling. Time zone differences, varying flight schedules, and communication barriers can lead to confusion and delays. Without proper coordination, team members might miss connections or arrive at different times, disrupting the purpose of the trip.',
      '## Leveraging Shared Workspaces',
      'Shared workspaces provide a centralized platform for all travel-related information. Tools like Cojauny allow team leaders to create events that include flight details, accommodation, and itinerary. This ensures everyone has access to the same information in real-time.',
      '### Benefits of Shared Workspaces',
      '- Centralized communication',
      '- Real-time updates',
      '- Easy access for all team members',
      '## Proactive Flight Updates',
      'Flight delays and cancellations are common. Proactive notifications keep everyone informed. Integrate with airline APIs to receive automatic updates and notify the team instantly.',
      '### How to Implement Proactive Updates',
      '1. Subscribe to flight status alerts',
      '2. Use apps that push notifications',
      '3. Designate a coordinator to monitor updates',
      '## Optimizing Meeting Points',
      'Choosing the right meeting points is crucial. For airports, select locations that are easy to find and have good signage. Use GPS coordinates and photos to guide team members.',
      '### Tips for Meeting Points',
      '- Choose central locations',
      '- Account for traffic and parking',
      '- Have backup plans',
      '## Reducing Regrouping Time',
      'By implementing these strategies, teams can reduce regrouping time by up to 50%. This allows more time for productive activities and less stress.',
      '## Case Studies',
      'Several companies have successfully implemented real-time coordination. For example, a tech startup reduced travel delays by 30% after adopting shared workspaces.',
      '## Conclusion',
      'Mastering real-time flight coordination is key to efficient distributed team travel. With the right tools and strategies, teams can travel seamlessly and focus on their goals. Start using Cojauny today to streamline your team\'s travel.'],
    tags: ['coordination', 'flights', 'teams'],
    categories: ['operations'],
    publishedAt: '2025-11-12T09:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 6
  },

  // POST-003..POST-006 (abbreviated)
  {
    postId: 'post-003', slug: 'minibus-team-coordination', locale: 'en', title: 'Advanced Minibus Coordination Strategies for Large Teams', summary: 'Guide to organizing minibuses and seat maps for teams of 8–15.', heroImage: '/images/og-default.svg', heroAlt: 'Minibus team', heroWidth: 1280, heroHeight: 720, body: ['# Minibus coordination', 'Plan capacity, assign seats and centralize communication to avoid last-minute issues.'], tags: ['minibus', 'teams'], categories: ['operations'], publishedAt: '2025-11-14T10:00:00.000Z', updatedAt: '2025-11-23T12:00:00.000Z', author: 'Cojauny Team', readingTimeMinutes: 6
  },

  {
    postId: 'post-004', slug: 'real-time-location-sharing', locale: 'en', title: 'Real-Time Location Sharing: Safety and Efficiency at Events', summary: 'How temporary location sharing helps teams regroup quickly while respecting privacy.', heroImage: '/images/og-default.svg', heroAlt: 'Location map', heroWidth: 1280, heroHeight: 720, body: ['# Real-Time Location Sharing: Safety and Efficiency at Events', '## Introduction', 'In the fast-paced world of events, real-time location sharing has emerged as a vital tool for teams. It enhances safety and efficiency by allowing members to locate each other quickly. This comprehensive guide explores how temporary location sharing works, its benefits, and how to implement it while respecting privacy.', '## The Importance of Location Sharing at Events', 'Events often involve large groups moving between locations. Without proper coordination, team members can get separated, leading to delays and stress. Real-time location sharing solves this by providing live updates on positions.', '## How Real-Time Location Sharing Works', 'Using GPS technology, apps track and share locations in real-time. Cojauny offers temporary sharing that activates only during event windows and automatically deletes data afterward.', '### Key Features', '- Temporary activation', '- Real-time updates', '- Automatic data removal', '## Benefits for Safety', 'Location sharing improves safety by allowing quick responses to emergencies. If someone is lost or in trouble, others can locate them instantly.', '### Efficiency Gains', 'It reduces regrouping time significantly. Teams can meet at exact spots without confusion.', '## Privacy and Ethical Considerations', 'Privacy is paramount. Always obtain consent from participants. Data should be handled securely and deleted promptly.', '### Best Practices for Privacy', '- Get explicit consent', '- Limit sharing duration', '- Use encrypted platforms', '## Implementing Location Sharing', 'Choose a reliable app. Set clear guidelines for use. Train team members on how to opt-in and opt-out.', '### Step-by-Step Guide', '1. Select a platform', '2. Define event parameters', '3. Obtain consents', '4. Monitor and manage', '## Potential Challenges', 'Technical issues like poor GPS signal or battery drain. Address by having backups.', '## Conclusion', 'Real-time location sharing is a game-changer for event coordination. When used responsibly, it boosts safety and efficiency. Start using Cojauny for your next event.'], tags: ['location', 'privacy'], categories: ['product'], publishedAt: '2025-11-15T11:00:00.000Z', updatedAt: '2025-11-23T12:00:00.000Z', author: 'Cojauny Team', readingTimeMinutes: 5
  },

  {
    postId: 'post-005', slug: 'ephemeral-group-chat', locale: 'en', title: 'Ephemeral Group Chats: Secure Communication That Self-Destructs', summary: 'Why ephemeral chats are ideal for event coordination.', heroImage: '/images/og-default.svg', heroAlt: 'Ephemeral chat', heroWidth: 1280, heroHeight: 720, body: ['# Ephemeral Group Chats: Secure Communication That Self-Destructs', '## Introduction', 'In the digital age, communication is key, but so is privacy. Ephemeral group chats offer a solution that allows secure, temporary conversations that self-destruct after a set period. This guide explores why these chats are ideal for event coordination and how they enhance security and reduce digital clutter.', '## What Are Ephemeral Chats?', 'Ephemeral chats are messaging threads that automatically delete themselves after a predetermined time, typically 24-48 hours. Unlike permanent chats, they leave no lasting trace, making them perfect for sensitive or time-bound discussions.', '## Benefits for Event Coordination', '### Enhanced Privacy', 'By auto-deleting messages, ephemeral chats protect sensitive information from being stored indefinitely. This is crucial for events where details like locations or personal data are shared.', '### Reduced Digital Footprint', 'They minimize the accumulation of old messages, keeping inboxes and chat histories clean. This reduces noise and helps focus on current tasks.', '### Encourages Timely Communication', 'Knowing messages will disappear encourages participants to respond promptly, speeding up coordination.', '## How Ephemeral Chats Work in Practice', 'Platforms like Cojauny integrate ephemeral chats into event workflows. Once an event ends, the chat self-destructs, ensuring no leftover data.', '### Key Features', '- Automatic deletion', '- Time-limited access', '- Secure encryption', '## Security Considerations', 'While beneficial, ensure the platform uses end-to-end encryption. Also, be aware that screenshots can still capture content before deletion.', '## Best Practices', '- Set clear expectations for participants', '- Use for event-related discussions only', '- Combine with other secure tools', '## Potential Drawbacks', 'Some users may forget important information if not noted elsewhere. Always have backups for critical details.', '## Conclusion', 'Ephemeral group chats are a powerful tool for secure, efficient event coordination. They balance communication needs with privacy concerns. Try Cojauny\'s ephemeral chats for your next event.'], tags: ['privacy', 'chat'], categories: ['product'], publishedAt: '2025-11-16T12:00:00.000Z', updatedAt: '2025-11-23T12:00:00.000Z', author: 'Cojauny Team', readingTimeMinutes: 4
  },

  {
    postId: 'post-006', slug: 'automatic-cost-splitting', locale: 'en', title: 'Automatic Cost Splitting: Clear Finances for Group Travel', summary: 'Automate expense splits to avoid spreadsheets and confusion.', heroImage: '/images/og-default.svg', heroAlt: 'Cost splitting', heroWidth: 1280, heroHeight: 720, body: ['# Cost splitting', 'Record expenses on the spot, split automatically and avoid disputes.'], tags: ['costs', 'splitting'], categories: ['product'], publishedAt: '2025-11-17T13:00:00.000Z', updatedAt: '2025-11-23T12:00:00.000Z', author: 'Cojauny Team', readingTimeMinutes: 5
  },

  // Translations for post-001 to post-006
  {
    postId: 'post-001',
    slug: 'share-airport-ride',
    locale: 'es',
    title: 'La guía definitiva para compartir viajes en aeropuerto con tu vuelo',
    summary: 'Un playbook práctico para alinear pasajeros, establecer puntos de encuentro y dividir traslados antes de tu viaje.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Viajeros de negocios organizando un viaje en aeropuerto',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# El playbook para compartir viajes en aeropuerto', 'Crea un evento de vuelo temprano, establece ventanas de recogida claras y acuerda pagos por adelantado.'],
    tags: ['viaje en aeropuerto', 'logística'],
    categories: ['operaciones', 'producto'],
    publishedAt: '2025-11-10T08:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Equipo Cojauny',
    readingTimeMinutes: 8
  },
  {
    postId: 'post-001',
    slug: 'share-airport-ride',
    locale: 'fr',
    title: 'Le guide ultime pour partager des trajets d’aéroport avec votre vol',
    summary: 'Un playbook pratique pour aligner les passagers, définir des points de rencontre et répartir les transferts avant votre voyage.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Voyageurs d’affaires organisant un trajet d’aéroport',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Le playbook pour partager des trajets d’aéroport', 'Créez un événement de vol tôt, définissez des fenêtres de prise en charge claires et convenez des paiements à l’avance.'],
    tags: ['trajet d’aéroport', 'logistique'],
    categories: ['opérations', 'produit'],
    publishedAt: '2025-11-10T08:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Équipe Cojauny',
    readingTimeMinutes: 8
  },
  {
    postId: 'post-001',
    slug: 'share-airport-ride',
    locale: 'de',
    title: 'Der ultimative Leitfaden zum Teilen von Flughafenfahrten mit Ihrem Flug',
    summary: 'Ein praktischer Leitfaden zur Abstimmung von Passagieren, Festlegung von Treffpunkten und Aufteilung von Transfers vor Ihrer Reise.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Geschäftsreisende organisieren eine Flughafenfahrt',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Der Leitfaden zum Teilen von Flughafenfahrten', 'Erstellen Sie frühzeitig ein Flugevent, legen Sie klare Abholfenster fest und vereinbaren Sie Zahlungen im Voraus.'],
    tags: ['flughafenfahrt', 'logistik'],
    categories: ['operationen', 'produkt'],
    publishedAt: '2025-11-10T08:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 8
  },
  {
    postId: 'post-002',
    slug: 'real-time-flight-coordination',
    locale: 'es',
    title: 'Dominando la coordinación de vuelos en tiempo real para equipos distribuidos',
    summary: 'Cómo espacios de trabajo compartidos, actualizaciones de vuelos y puntos de encuentro reducen el tiempo de reagrupación para equipos.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Equipo coordinando vuelos',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Coordinación de vuelos en tiempo real', 'Usa espacios de trabajo de viaje y notificaciones proactivas para mantener a los equipos sincronizados.'],
    tags: ['coordinación', 'vuelos', 'equipos'],
    categories: ['operaciones'],
    publishedAt: '2025-11-12T09:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Equipo Cojauny',
    readingTimeMinutes: 8
  },
  {
    postId: 'post-002',
    slug: 'real-time-flight-coordination',
    locale: 'fr',
    title: 'Maîtriser la coordination de vol en temps réel pour les équipes distribuées',
    summary: 'Comment les espaces de travail partagés, les mises à jour de vol et les points de rencontre réduisent le temps de regroupement pour les équipes.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Équipe coordonnant les vols',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Coordination de vol en temps réel', 'Utilisez des espaces de travail de voyage et des notifications proactives pour garder les équipes synchronisées.'],
    tags: ['coordination', 'vols', 'équipes'],
    categories: ['opérations'],
    publishedAt: '2025-11-12T09:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Équipe Cojauny',
    readingTimeMinutes: 8
  },
  {
    postId: 'post-002',
    slug: 'real-time-flight-coordination',
    locale: 'de',
    title: 'Echtzeit-Flugkoordination für verteilte Teams meistern',
    summary: 'Wie gemeinsame Arbeitsbereiche, Flugaktualisierungen und Treffpunkte die Wiedergruppierungszeit für Teams reduzieren.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Team koordiniert Flüge',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Echtzeit-Flugkoordination', 'Verwenden Sie Reise-Arbeitsbereiche und proaktive Benachrichtigungen, um Teams synchron zu halten.'],
    tags: ['koordination', 'flüge', 'teams'],
    categories: ['operationen'],
    publishedAt: '2025-11-12T09:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 8
  },
  {
    postId: 'post-003',
    slug: 'minibus-team-coordination',
    locale: 'es',
    title: 'Estrategias avanzadas de coordinación de minibuses para equipos grandes',
    summary: 'Guía para organizar minibuses y mapas de asientos para equipos de 8–15.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Equipo de minibus',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Coordinación de minibuses', 'Planifica la capacidad, asigna asientos y centraliza la comunicación para evitar problemas de último minuto.'],
    tags: ['minibus', 'equipos'],
    categories: ['operaciones'],
    publishedAt: '2025-11-14T10:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Equipo Cojauny',
    readingTimeMinutes: 6
  },
  {
    postId: 'post-003',
    slug: 'minibus-team-coordination',
    locale: 'fr',
    title: 'Stratégies avancées de coordination de minibus pour les grandes équipes',
    summary: 'Guide pour organiser les minibus et les cartes de sièges pour les équipes de 8–15.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Équipe de minibus',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Coordination de minibus', 'Planifiez la capacité, attribuez des sièges et centralisez la communication pour éviter les problèmes de dernière minute.'],
    tags: ['minibus', 'équipes'],
    categories: ['opérations'],
    publishedAt: '2025-11-14T10:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Équipe Cojauny',
    readingTimeMinutes: 6
  },
  {
    postId: 'post-003',
    slug: 'minibus-team-coordination',
    locale: 'de',
    title: 'Erweiterte Minibus-Koordinationsstrategien für große Teams',
    summary: 'Leitfaden zur Organisation von Minibussen und Sitzplänen für Teams von 8–15.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Minibus-Team',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Minibus-Koordination', 'Planen Sie die Kapazität, weisen Sie Sitze zu und zentralisieren Sie die Kommunikation, um Probleme im letzten Moment zu vermeiden.'],
    tags: ['minibus', 'teams'],
    categories: ['operationen'],
    publishedAt: '2025-11-14T10:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 6
  },
  {
    postId: 'post-004',
    slug: 'real-time-location-sharing',
    locale: 'es',
    title: 'Compartir ubicación en tiempo real: Seguridad y eficiencia en eventos',
    summary: 'Cómo el intercambio temporal de ubicación ayuda a los equipos a reagruparse rápidamente mientras respeta la privacidad.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Mapa de ubicación',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Compartir ubicación', 'Habilita el intercambio temporal durante las ventanas de eventos; los datos se eliminan después para proteger la privacidad.'],
    tags: ['ubicación', 'privacidad'],
    categories: ['producto'],
    publishedAt: '2025-11-15T11:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Equipo Cojauny',
    readingTimeMinutes: 5
  },
  {
    postId: 'post-004',
    slug: 'real-time-location-sharing',
    locale: 'fr',
    title: 'Partage de localisation en temps réel : Sécurité et efficacité lors des événements',
    summary: 'Comment le partage temporaire de localisation aide les équipes à se regrouper rapidement tout en respectant la confidentialité.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Carte de localisation',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Partage de localisation', 'Activez le partage temporaire pendant les fenêtres d’événement ; les données sont supprimées ensuite pour protéger la confidentialité.'],
    tags: ['localisation', 'confidentialité'],
    categories: ['produit'],
    publishedAt: '2025-11-15T11:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Équipe Cojauny',
    readingTimeMinutes: 5
  },
  {
    postId: 'post-004',
    slug: 'real-time-location-sharing',
    locale: 'de',
    title: 'Echtzeit-Standortfreigabe: Sicherheit und Effizienz bei Events',
    summary: 'Wie die temporäre Standortfreigabe Teams hilft, sich schnell wieder zu gruppieren, während die Privatsphäre respektiert wird.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Standortkarte',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Standortfreigabe', 'Aktivieren Sie die temporäre Freigabe während Event-Fenstern; Daten werden anschließend entfernt, um die Privatsphäre zu schützen.'],
    tags: ['standort', 'datenschutz'],
    categories: ['produkt'],
    publishedAt: '2025-11-15T11:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 5
  },
  {
    postId: 'post-005',
    slug: 'ephemeral-group-chat',
    locale: 'es',
    title: 'Chats grupales efímeros: Comunicación segura que se autodestruye',
    summary: 'Por qué los chats efímeros son ideales para la coordinación de eventos.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Chat efímero',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Chats efímeros', 'Los chats se autoeliminan después de 48 horas del evento para reducir la huella digital y el ruido.'],
    tags: ['privacidad', 'chat'],
    categories: ['producto'],
    publishedAt: '2025-11-16T12:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Equipo Cojauny',
    readingTimeMinutes: 4
  },
  {
    postId: 'post-005',
    slug: 'ephemeral-group-chat',
    locale: 'fr',
    title: 'Chats de groupe éphémères : Communication sécurisée qui s’auto-détruit',
    summary: 'Pourquoi les chats éphémères sont idéaux pour la coordination d’événements.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Chat éphémère',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Chats éphémères', 'Les chats s’auto-suppriment 48 heures après l’événement pour réduire l’empreinte numérique et le bruit.'],
    tags: ['confidentialité', 'chat'],
    categories: ['produit'],
    publishedAt: '2025-11-16T12:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Équipe Cojauny',
    readingTimeMinutes: 4
  },
  {
    postId: 'post-005',
    slug: 'ephemeral-group-chat',
    locale: 'de',
    title: 'Ephemere Gruppenchats: Sichere Kommunikation, die sich selbst zerstört',
    summary: 'Warum ephemere Chats ideal für die Eventkoordination sind.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Ephemerer Chat',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Ephemere Chats', 'Chats werden 48 Stunden nach dem Event automatisch gelöscht, um die digitale Fußspur und den Lärm zu reduzieren.'],
    tags: ['datenschutz', 'chat'],
    categories: ['produkt'],
    publishedAt: '2025-11-16T12:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 4
  },
  {
    postId: 'post-006',
    slug: 'automatic-cost-splitting',
    locale: 'es',
    title: 'División automática de costos: Finanzas claras para viajes grupales',
    summary: 'Automatiza la división de gastos para evitar hojas de cálculo y confusiones.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'División de costos',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# División de costos', 'Registra gastos en el momento, divide automáticamente y evita disputas.'],
    tags: ['costos', 'división'],
    categories: ['producto'],
    publishedAt: '2025-11-17T13:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Equipo Cojauny',
    readingTimeMinutes: 5
  },
  {
    postId: 'post-006',
    slug: 'automatic-cost-splitting',
    locale: 'fr',
    title: 'Partage automatique des coûts : Finances claires pour les voyages de groupe',
    summary: 'Automatisez le partage des dépenses pour éviter les feuilles de calcul et les confusions.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Partage des coûts',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Partage des coûts', 'Enregistrez les dépenses sur le moment, partagez automatiquement et évitez les disputes.'],
    tags: ['coûts', 'partage'],
    categories: ['produit'],
    publishedAt: '2025-11-17T13:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Équipe Cojauny',
    readingTimeMinutes: 5
  },
  {
    postId: 'post-006',
    slug: 'automatic-cost-splitting',
    locale: 'de',
    title: 'Automatische Kostenaufteilung: Klare Finanzen für Gruppenreisen',
    summary: 'Automatisieren Sie die Aufteilung von Ausgaben, um Tabellenkalkulationen und Verwirrungen zu vermeiden.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Kostenaufteilung',
    heroWidth: 1280,
    heroHeight: 720,
    body: ['# Kostenaufteilung', 'Erfassen Sie Ausgaben sofort, teilen Sie automatisch auf und vermeiden Sie Streitigkeiten.'],
    tags: ['kosten', 'aufteilung'],
    categories: ['produkt'],
    publishedAt: '2025-11-17T13:00:00.000Z',
    updatedAt: '2025-11-23T12:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 5
  },

  // === New posts: Madrid guide in EN/ES/FR/DE ===
  {
    postId: 'post-007',
    slug: 'share-taxi-madrid-barajas',
    locale: 'en',
    title: 'How to Share a Taxi from Madrid–Barajas (MAD) — Practical Guide',
    summary: 'Step-by-step guide to sharing taxis at Madrid–Barajas: meeting points, timing, cost-splitting and driver coordination.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Passengers meeting at Madrid airport to share a taxi',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Share a Taxi at Madrid–Barajas (MAD): A Practical Guide',
      'Madrid–Barajas is a busy international hub. Sharing a taxi after arrival can save significant money and reduce the hassle of finding group transport. This guide helps you pick the right meeting point, set a realistic pickup window and split costs fairly using Cojauny.',
      '## Choose the best meeting point',
      'For arrivals, use "Exit 3 - Arrivals Level" or the main taxi rank outside Terminal 4 if your flight arrives there. For departures, meet by the short-term parking entrance or a named coffee shop inside the terminal. Pin a precise location and add a photo to avoid confusion.',
      '## Set realistic pickup windows',
      'Allow 20–30 minutes from gate arrival for passport control and luggage. When creating your event, choose a 30-minute slot and add a 15-minute buffer to reduce missed connections.',
      '## Coordinate with the driver and payment',
      'Ask the driver to announce license plate and car model in the event chat, and decide payment method upfront. Use Cojauny’s cost splitter to calculate each person’s share and post payment links for convenience.',
       '## Quick checklist (MAD)',
       '- Pin exact meeting point with photo',
       '- Set 30-minute pickup window',
       '- Confirm driver plate in chat',
       '- Split cost before boarding',
      '## CTA: Try it on Cojauny',
      'Create your event now, share the link with co-travelers and get an instant estimate of the savings for your trip from Madrid–Barajas.'
    ],
    tags: ['airport', 'madrid', 'taxi', 'travel'],
    categories: ['product', 'seo'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 4
  },

  {
    postId: 'post-007',
    slug: 'share-taxi-madrid-barajas',
    locale: 'es',
    title: 'Cómo compartir un taxi desde Madrid–Barajas (MAD): Guía práctica',
    summary: 'Guía paso a paso para compartir taxis en Madrid–Barajas: puntos de encuentro, horarios, división de costos y coordinación con conductores.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Pasajeros encontrándose en el aeropuerto de Madrid para compartir un taxi',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Cómo compartir un taxi en Madrid–Barajas (MAD): Guía práctica',
      'Madrid–Barajas es un importante centro internacional. Compartir un taxi después de llegar puede ahorrar dinero y reducir el estrés de encontrar transporte grupal. Esta guía te ayuda a elegir el mejor punto de encuentro, establecer una ventana de recogida realista y dividir los costos de manera justa usando Cojauny.',
      '## Elige el mejor punto de encuentro',
      'Para llegadas, utiliza "Salida 3 - Nivel de Llegadas" o la parada de taxis principal fuera de la Terminal 4 si tu vuelo llega allí. Para salidas, reúne al grupo en la entrada del estacionamiento de corta duración o en una cafetería dentro de la terminal. Fija una ubicación precisa y añade una foto para evitar confusiones.',
      '## Establece ventanas de recogida realistas',
      'Permite de 20 a 30 minutos desde la llegada a la puerta para el control de pasaportes y el equipaje. Al crear tu evento, elige un intervalo de 30 minutos y añade un margen de 15 minutos para reducir conexiones perdidas.',
      '## Coordina con el conductor y el pago',
      'Pide al conductor que anuncie la matrícula y el modelo del coche en el chat del evento, y decide el método de pago por adelantado. Usa la herramienta de división de costos de Cojauny para calcular la parte de cada persona y publica enlaces de pago para mayor comodidad.',
      '## Lista rápida (MAD)',
      '- Fija un punto de encuentro exacto con foto',
      '- Establece una ventana de recogida de 30 minutos',
      '- Confirma la matrícula del conductor en el chat',
      '- Divide el costo antes de abordar',
      '## CTA: Pruébalo en Cojauny',
      'Crea tu evento ahora, comparte el enlace con tus compañeros de viaje y obtén una estimación instantánea de los ahorros para tu viaje desde Madrid–Barajas.'
    ], tags: ['aeropuerto', 'madrid', 'taxi', 'viaje'], categories: ['producto', 'seo'], publishedAt: '2025-11-27T10:00:00.000Z', updatedAt: '2025-11-27T10:00:00.000Z', author: 'Equipo Cojauny', readingTimeMinutes: 4
  },
  {
    postId: 'post-007',
    slug: 'share-taxi-madrid-barajas',
    locale: 'fr',
    title: 'Comment partager un taxi depuis Madrid–Barajas (MAD) : Guide pratique',
    summary: 'Guide étape par étape pour partager des taxis à Madrid–Barajas : points de rencontre, horaires, partage des coûts et coordination avec les chauffeurs.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Passagers se rencontrant à l’aéroport de Madrid pour partager un taxi',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Comment partager un taxi à Madrid–Barajas (MAD) : Guide pratique',
      'Madrid–Barajas est un hub international très fréquenté. Partager un taxi après l’arrivée peut permettre d’économiser de l’argent et de réduire le stress lié à la recherche d’un transport de groupe. Ce guide vous aide à choisir le meilleur point de rencontre, à définir une fenêtre de prise en charge réaliste et à partager les coûts équitablement avec Cojauny.',
      '## Choisissez le meilleur point de rencontre',
      'Pour les arrivées, utilisez "Sortie 3 - Niveau des Arrivées" ou la station de taxis principale à l’extérieur du Terminal 4 si votre vol arrive là. Pour les départs, retrouvez le groupe à l’entrée du parking de courte durée ou dans un café nommé à l’intérieur du terminal. Fixez un lieu précis et ajoutez une photo pour éviter toute confusion.',
      '## Définissez des fenêtres de prise en charge réalistes',
      'Prévoyez 20 à 30 minutes depuis l’arrivée à la porte pour le contrôle des passeports et les bagages. Lors de la création de votre événement, choisissez un créneau de 30 minutes et ajoutez une marge de 15 minutes pour réduire les connexions manquées.',
      '## Coordonnez avec le chauffeur et le paiement',
      'Demandez au chauffeur d’annoncer la plaque d’immatriculation et le modèle de la voiture dans le chat de l’événement, et décidez du mode de paiement à l’avance. Utilisez l’outil de partage des coûts de Cojauny pour calculer la part de chaque personne et publiez des liens de paiement pour plus de commodité.',
      '## Liste rapide (MAD)',
      '- Fixez un point de rencontre précis avec photo',
      '- Définissez une fenêtre de prise en charge de 30 minutes',
      '- Confirmez la plaque d’immatriculation du chauffeur dans le chat',
      '- Partagez les coûts avant de monter',
      '## CTA : Essayez Cojauny',
      'Créez votre événement maintenant, partagez le lien avec vos compagnons de voyage et obtenez une estimation instantanée des économies pour votre trajet depuis Madrid–Barajas.'
    ], tags: ['aéroport', 'madrid', 'taxi', 'voyage'], categories: ['produit', 'seo'], publishedAt: '2025-11-27T10:00:00.000Z', updatedAt: '2025-11-27T10:00:00.000Z', author: 'Équipe Cojauny', readingTimeMinutes: 4
  },
  {
    postId: 'post-007',
    slug: 'share-taxi-madrid-barajas',
    locale: 'de',
    title: 'Wie man ein Taxi vom Flughafen Madrid–Barajas (MAD) teilt: Praktischer Leitfaden',
    summary: 'Schritt-für-Schritt-Anleitung zum Teilen von Taxis am Flughafen Madrid–Barajas: Treffpunkte, Zeitfenster, Kostenaufteilung und Fahrerkoordination.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Passagiere treffen sich am Flughafen Madrid, um ein Taxi zu teilen',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Wie man ein Taxi am Flughafen Madrid–Barajas (MAD) teilt: Praktischer Leitfaden',
      'Madrid–Barajas ist ein geschäftiger internationaler Knotenpunkt. Das Teilen eines Taxis nach der Ankunft kann erheblich Geld sparen und den Stress bei der Suche nach Gruppentransporten reduzieren. Dieser Leitfaden hilft Ihnen, den besten Treffpunkt auszuwählen, ein realistisches Abholzeitfenster festzulegen und die Kosten fair mit Cojauny zu teilen.',
      '## Wählen Sie den besten Treffpunkt',
      'Für Ankünfte nutzen Sie "Ausgang 3 - Ankunftsebene" oder den Haupttaxistand außerhalb von Terminal 4, wenn Ihr Flug dort ankommt. Für Abflüge treffen Sie sich am Eingang des Kurzzeitparkplatzes oder in einem benannten Café im Terminal. Markieren Sie einen genauen Standort und fügen Sie ein Foto hinzu, um Verwirrung zu vermeiden.',
      '## Legen Sie realistische Abholzeitfenster fest',
      'Planen Sie 20–30 Minuten ab Gate-Ankunft für Passkontrolle und Gepäck ein. Wählen Sie bei der Erstellung Ihres Events ein 30-Minuten-Zeitfenster und fügen Sie einen Puffer von 15 Minuten hinzu, um verpasste Verbindungen zu reduzieren.',
      '## Koordinieren Sie mit dem Fahrer und der Zahlung',
      'Bitten Sie den Fahrer, das Kennzeichen und das Automodell im Event-Chat anzukündigen, und legen Sie die Zahlungsmethode im Voraus fest. Verwenden Sie das Kostenaufteilungstool von Cojauny, um den Anteil jeder Person zu berechnen, und veröffentlichen Sie Zahlungslinks für mehr Komfort.',
      '## Schnelle Checkliste (MAD)',
      '- Markieren Sie einen genauen Treffpunkt mit Foto',
      '- Legen Sie ein 30-Minuten-Abholzeitfenster fest',
      '- Bestätigen Sie das Kennzeichen des Fahrers im Chat',
      '- Teilen Sie die Kosten vor dem Einsteigen',
      '## CTA: Probieren Sie Cojauny aus',
      'Erstellen Sie jetzt Ihr Event, teilen Sie den Link mit Ihren Mitreisenden und erhalten Sie eine sofortige Schätzung der Einsparungen für Ihre Reise ab Madrid–Barajas.'
    ], tags: ['flughafen', 'madrid', 'taxi', 'reise'], categories: ['produkt', 'seo'], publishedAt: '2025-11-27T10:00:00.000Z', updatedAt: '2025-11-27T10:00:00.000Z', author: 'Cojauny Team', readingTimeMinutes: 4
  },

  // POST-008..012 (EN) abbreviated
  {
    postId: 'post-008',
    slug: 'share-taxi-london-heathrow',
    locale: 'en',
    title: 'Sharing a Taxi at London Heathrow (LHR): Where to Meet and How to Save',
    summary: 'Practical advice for coordinating shared taxis at Heathrow: terminals, pick-up zones and tips to avoid delays.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Group of travelers sharing a taxi at Heathrow airport',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Share a Taxi at London Heathrow (LHR): Tips and Meeting Points',
      'Heathrow is one of the world’s busiest airports. Properly coordinating meeting points and timing is the key to a smooth shared taxi experience. Cojauny helps teams and travelers lock down the details quickly.',
      '## Terminal-specific meeting points',
      'Terminal 2 and 3 share similar public areas — prefer the arrivals hall coffee shop or a named shop. Terminal 5 has a main taxi rank; pin the closest lane and instruct participants to wait by the Terminal sign.',
      '## Avoiding congestion',
      'When flights are delayed, shift the pickup automatically in your event and notify participants. Use the chat to confirm a single point of contact to meet the driver.',
      '## Safety and verification',
      'Always ask for the driver plate and take a quick photo when the car arrives. Cojauny stores that plate in the event log for traceability.',
      '## CTA: Organize your Heathrow ride',
      'Start an event on Cojauny for LHR and send the invite link. Everyone sees the pickup point and the estimated savings instantly.'
    ],
    tags: ['airport', 'heathrow', 'taxi', 'travel'],
    categories: ['product', 'seo'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 4
  },
  {
    postId: 'post-008',
    slug: 'share-taxi-london-heathrow',
    locale: 'es',
    title: 'Cómo compartir un taxi en Londres Heathrow (LHR): Dónde reunirse y cómo ahorrar',
    summary: 'Consejos prácticos para coordinar taxis compartidos en Heathrow: terminales, zonas de recogida y cómo evitar retrasos.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Grupo de viajeros compartiendo un taxi en el aeropuerto de Heathrow',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Cómo compartir un taxi en Londres Heathrow (LHR): Consejos y puntos de encuentro',
      'Heathrow es uno de los aeropuertos más concurridos del mundo. Coordinar correctamente los puntos de encuentro y los horarios es clave para una experiencia fluida de taxi compartido. Cojauny ayuda a equipos y viajeros a organizar los detalles rápidamente.',
      '## Puntos de encuentro específicos por terminal',
      'Las terminales 2 y 3 comparten áreas públicas similares: prefiera la cafetería del hall de llegadas o una tienda nombrada. La terminal 5 tiene una parada principal de taxis; marque el carril más cercano e indique a los participantes que esperen junto al letrero de la terminal.',
      '## Evitar la congestión',
      'Cuando los vuelos se retrasan, ajuste automáticamente la recogida en su evento y notifique a los participantes. Use el chat para confirmar un único punto de contacto para reunirse con el conductor.',
      '## Seguridad y verificación',
      'Siempre pida la matrícula del conductor y tome una foto rápida cuando llegue el coche. Cojauny almacena esa matrícula en el registro del evento para trazabilidad.',
      '## CTA: Organiza tu viaje en Heathrow',
      'Crea un evento en Cojauny para LHR y envía el enlace de invitación. Todos ven el punto de recogida y los ahorros estimados al instante.'
    ],
    tags: ['aeropuerto', 'heathrow', 'taxi', 'viaje'],
    categories: ['producto', 'seo'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Equipo Cojauny',
    readingTimeMinutes: 4
  },
  {
    postId: 'post-008',
    slug: 'share-taxi-london-heathrow',
    locale: 'fr',
    title: 'Comment partager un taxi depuis Londres Heathrow (LHR) : Où se retrouver et comment économiser',
    summary: 'Conseils pratiques pour coordonner les taxis partagés à Heathrow : terminaux, zones de prise en charge et astuces pour éviter les retards.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Groupe de voyageurs partageant un taxi à l’aéroport de Heathrow',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Comment partager un taxi à Londres Heathrow (LHR) : Conseils et points de rencontre',
      'Heathrow est l’un des aéroports les plus fréquentés au monde. Une bonne coordination des points de rencontre et des horaires est la clé d’une expérience fluide de taxi partagé. Cojauny aide les équipes et les voyageurs à verrouiller rapidement les détails.',
      '## Points de rencontre spécifiques aux terminaux',
      'Les terminaux 2 et 3 partagent des zones publiques similaires : préférez le café du hall des arrivées ou une boutique nommée. Le terminal 5 a un rang de taxis principal ; épinglez la voie la plus proche et indiquez aux participants d’attendre près du panneau du terminal.',
      '## Éviter la congestion',
      'Lorsque les vols sont retardés, déplacez automatiquement le ramassage dans votre événement et informez les participants. Utilisez le chat pour confirmer un seul point de contact pour rencontrer le conducteur.',
      '## Sécurité et vérification',
      'Demandez toujours la plaque d’immatriculation du conducteur et prenez une photo rapide lorsque la voiture arrive. Cojauny stocke cette plaque dans le journal de l’événement pour la traçabilité.',
      '## CTA : Organisez votre course à Heathrow',
      'Démarrez un événement sur Cojauny pour LHR et envoyez le lien d’invitation. Tout le monde voit le point de ramassage et les économies estimées instantanément.'
    ],
    tags: ['aéroport', 'heathrow', 'taxi', 'voyage'],
    categories: ['produit', 'seo'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Équipe Cojauny',
    readingTimeMinutes: 4
  },
  {
    postId: 'post-008',
    slug: 'share-taxi-london-heathrow',
    locale: 'de',
    title: 'Wie man ein Taxi vom Flughafen London Heathrow (LHR) teilt: Wo man sich trifft und wie man spart',
    summary: 'Praktische Tipps zur Koordination von Shared Taxis in Heathrow: Terminals, Abholzonen und Tipps zur Vermeidung von Verzögerungen.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Gruppe von Reisenden, die ein Taxi am Flughafen Heathrow teilen',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Wie man ein Taxi am Flughafen London Heathrow (LHR) teilt: Tipps und Treffpunkte',
      'Heathrow ist einer der verkehrsreichsten Flughäfen der Welt. Die richtige Koordination von Treffpunkten und Zeiten ist der Schlüssel zu einer reibungslosen Erfahrung mit Shared Taxis. Cojauny hilft Teams und Reisenden, die Details schnell festzulegen.',
      '## Terminal-spezifische Treffpunkte',
      'Terminal 2 und 3 teilen sich ähnliche öffentliche Bereiche - bevorzugen Sie das Café in der Ankunftshalle oder ein benanntes Geschäft. Terminal 5 hat einen Haupttaxistand; markieren Sie die nächstgelegene Spur und weisen Sie die Teilnehmer an, am Terminal-Schild zu warten.',
      '## Vermeidung von Staus',
      'Wenn Flüge verspätet sind, verschieben Sie die Abholung automatisch in Ihrem Event und benachrichtigen Sie die Teilnehmer. Nutzen Sie den Chat, um einen einzigen Ansprechpartner für das Treffen mit dem Fahrer zu bestätigen.',
      '## Sicherheit und Verifizierung',
      'Fragen Sie immer nach dem Kennzeichen des Fahrers und machen Sie ein schnelles Foto, wenn das Auto ankommt. Cojauny speichert dieses Kennzeichen im Veranstaltungsprotokoll zur Nachverfolgbarkeit.',
      '## CTA: Organisieren Sie Ihre Fahrt nach Heathrow',
      'Starten Sie ein Event auf Cojauny für LHR und senden Sie den Einladungslink. Jeder sieht sofort den Abholpunkt und die geschätzten Einsparungen.'
    ],
    tags: ['flughafen', 'heathrow', 'taxi', 'reise'],
    categories: ['produkt', 'seo'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 4
  },

  // POST-009..012 (EN) abbreviated
  {
    postId: 'post-009',
    slug: 'share-taxi-amsterdam-schiphol',
    locale: 'en',
    title: 'Sharing a Taxi at Amsterdam Schiphol (AMS): Tips for Travelers',
    summary: 'Essential tips for meeting points, timing, and cost-saving when sharing taxis at Schiphol.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Travelers sharing a taxi at Amsterdam Schiphol airport',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Share a Taxi at Amsterdam Schiphol (AMS): Essential Tips',
      'Schiphol is a major European airport with unique challenges for taxi sharing. This guide provides key tips to ensure a seamless experience.',
      '## Preferred meeting points',
      'Always prefer the designated taxi meeting points at Schiphol. These are well-known to drivers and ensure a safer, more reliable pickup.',
      '## Timing considerations',
      'Factor in extra time for passport control and baggage claim. It’s advisable to set your pickup time 30 minutes after landing at the earliest.',
      '## Using the Cojauny app',
      'Create your taxi-sharing event on Cojauny as soon as you land. This allows for real-time updates and easy communication with your driver and co-travelers.',
      '## CTA: Start your Cojauny event',
      'Don’t leave your taxi arrangements to chance. Start an event on Cojauny now and enjoy a hassle-free taxi sharing experience at Schiphol.'
    ],
    tags: ['airport', 'schiphol', 'taxi', 'travel'],
    categories: ['product', 'seo'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 4
  },
  {
    postId: 'post-009',
    slug: 'share-taxi-amsterdam-schiphol',
    locale: 'es',
    title: 'Cómo compartir un taxi en Ámsterdam Schiphol (AMS): Consejos para viajeros',
    summary: 'Consejos esenciales sobre puntos de encuentro, horarios y ahorro de costos al compartir taxis en Schiphol.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Viajeros compartiendo un taxi en el aeropuerto de Ámsterdam Schiphol',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Cómo compartir un taxi en Ámsterdam Schiphol (AMS): Consejos esenciales',
      'Schiphol es un importante aeropuerto europeo con desafíos únicos para compartir taxis. Esta guía proporciona consejos clave para asegurar una experiencia sin inconvenientes.',
      '## Puntos de encuentro preferidos',
      'Siempre prefiera los puntos de encuentro designados para taxis en Schiphol. Estos son bien conocidos por los conductores y aseguran una recogida más segura y confiable.',
      '## Consideraciones de tiempo',
      'Tenga en cuenta el tiempo adicional para el control de pasaportes y la recogida de equipajes. Se recomienda establecer la hora de recogida al menos 30 minutos después del aterrizaje.',
      '## Uso de la app Cojauny',
      'Cree su evento de compartición de taxi en Cojauny tan pronto como aterrice. Esto permite actualizaciones en tiempo real y una comunicación fácil con su conductor y compañeros de viaje.',
      '## CTA: Inicie su evento Cojauny',
      'No deje sus arreglos de taxi al azar. Inicie un evento en Cojauny ahora y disfrute de una experiencia de compartición de taxi sin complicaciones en Schiphol.'
    ],
    tags: ['aeropuerto', 'schiphol', 'taxi', 'viaje'],
    categories: ['producto', 'seo'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Equipo Cojauny',
    readingTimeMinutes: 4
  },
  {
    postId: 'post-009',
    slug: 'share-taxi-amsterdam-schiphol',
    locale: 'fr',
    title: 'Comment partager un taxi à l’aéroport d’Amsterdam Schiphol (AMS) : Conseils pour les voyageurs',
    summary: 'Conseils essentiels sur les points de rencontre, le timing et les économies de coûts lors du partage de taxis à Schiphol.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Voyageurs partageant un taxi à l’aéroport d’Amsterdam Schiphol',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Comment partager un taxi à l’aéroport d’Amsterdam Schiphol (AMS) : Conseils essentiels',
      'Schiphol est un aéroport européen majeur avec des défis uniques pour le partage de taxis. Ce guide fournit des conseils clés pour garantir une expérience sans accroc.',
      '## Points de rencontre préférés',
      'Privilégiez toujours les points de rencontre désignés pour les taxis à Schiphol. Ils sont bien connus des conducteurs et garantissent une prise en charge plus sûre et plus fiable.',
      '## Considérations temporelles',
      'Prévoyez du temps supplémentaire pour le contrôle des passeports et la récupération des bagages. Il est conseillé de fixer l’heure de prise en charge 30 minutes après l’atterrissage au plus tôt.',
      '## Utilisation de l’application Cojauny',
      'Créez votre événement de partage de taxi sur Cojauny dès votre atterrissage. Cela permet des mises à jour en temps réel et une communication facile avec votre conducteur et vos co-voyageurs.',
      '## CTA : Démarrez votre événement Cojauny',
      'Ne laissez pas vos arrangements de taxi au hasard. Démarrez un événement sur Cojauny maintenant et profitez d’une expérience de partage de taxi sans tracas à Schiphol.'
    ],
    tags: ['aéroport', 'schiphol', 'taxi', 'voyage'],
    categories: ['produit', 'seo'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Équipe Cojauny',
    readingTimeMinutes: 4
  },
  {
    postId: 'post-009',
    slug: 'share-taxi-amsterdam-schiphol',
    locale: 'de',
    title: 'Wie man ein Taxi am Flughafen Amsterdam Schiphol (AMS) teilt: Tipps für Reisende',
    summary: 'Wichtige Tipps zu Treffpunkten, Zeiten und Kostenersparnissen beim Teilen von Taxis in Schiphol.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Reisende teilen ein Taxi am Flughafen Amsterdam Schiphol',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Wie man ein Taxi am Flughafen Amsterdam Schiphol (AMS) teilt: Wichtige Tipps',
      'Schiphol ist ein wichtiger europäischer Flughafen mit besonderen Herausforderungen beim Taxi teilen. Dieser Leitfaden gibt Ihnen wichtige Tipps, um ein reibungsloses Erlebnis zu gewährleisten.',
      '## Bevorzugte Treffpunkte',
      'Bevorzugen Sie immer die vorgesehenen Treffpunkte für Taxis in Schiphol. Diese sind den Fahrern gut bekannt und sorgen für eine sicherere und zuverlässigere Abholung.',
      '## Zeitliche Überlegungen',
      'Berücksichtigen Sie zusätzliche Zeit für die Passkontrolle und die Gepäckausgabe. Es ist ratsam, die Abholzeit frühestens 30 Minuten nach der Landung festzulegen.',
      '## Nutzung der Cojauny-App',
      'Erstellen Sie Ihr Taxi-Sharing-Event auf Cojauny, sobald Sie gelandet sind. So sind Sie in der Lage, Echtzeit-Updates zu erhalten und einfach mit Ihrem Fahrer und Mitreisenden zu kommunizieren.',
      '## CTA: Starten Sie Ihr Cojauny-Event',
      'Überlassen Sie Ihre Taxiarrangements nicht dem Zufall. Starten Sie jetzt ein Event auf Cojauny und genießen Sie ein stressfreies Taxi-Sharing-Erlebnis in Schiphol.'
    ],
    tags: ['flughafen', 'schiphol', 'taxi', 'reise'],
    categories: ['produkt', 'seo'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 4
  },
  {
    postId: 'post-010',
    slug: 'case-study-corporate-pilot',
    locale: 'en',
    title: 'Case Study: How a Corporate Pilot Reduced Transfer Costs by 48%',
    summary: 'Real results from the pilot: savings, time improvements, and lessons learned from a corporate Cojauny trial with a 120-person conference.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Corporate team using Cojauny at an event',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Case Study: Corporate Pilot — 120-Person Conference',
      'We conducted a pilot with a medium-sized company attending a multi-day conference. The goal: reduce transfer costs and coordination time. The results were measurable and instructive.',
      '## The Setup',
      'We created a travel workspace, added flights for 120 attendees, and segmented transfers by arrival windows. Organizers used Cojauny to propose meeting points and capacity per trip.',
      '## Results',
      '- Average transfer cost reduced by 48%',
      '- Average regrouping time reduced from 45 min to 12 min',
      '- 92% of attendees used Cojauny to confirm pickup',
      '## Key Lessons',
      'Early communication, a single point of contact (link with the driver), and clear pickup windows were the biggest drivers of success. Organizers who prepared accurate meeting photos and pins had nearly perfect on-time pickups.',
      '## CTA: Run Your Pilot',
      'Contact our team to design a pilot for your organization and get a personalized ROI estimate.'
    ],
    tags: ['case study', 'corporate', 'pilots', 'operations'],
    categories: ['operations', 'product'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 6
  },
  {
    postId: 'post-010',
    slug: 'case-study-corporate-pilot',
    locale: 'es',
    title: 'Estudio de caso: Cómo un piloto corporativo redujo los costos de traslado en un 48%',
    summary: 'Resultados reales del piloto: ahorros, mejoras de tiempo y lecciones aprendidas de una prueba corporativa de Cojauny con una conferencia de 120 personas.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Equipo corporativo usando Cojauny en un evento',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Estudio de caso: Piloto corporativo — Conferencia de 120 personas',
      'Realizamos un piloto con una empresa mediana que asistía a una conferencia de varios días. El objetivo: reducir los costos de traslado y el tiempo de coordinación. Los resultados fueron medibles e instructivos.',
      '## La configuración',
      'Creamos un espacio de trabajo de viaje, añadimos vuelos para 120 asistentes y segmentamos los traslados por ventanas de llegada. Los organizadores usaron Cojauny para proponer puntos de encuentro y capacidad por viaje.',
      '## Resultados',
      '- Costo promedio de traslado reducido en un 48%',
      '- Tiempo promedio de reagrupación reducido de 45 min a 12 min',
      '- El 92% de los asistentes usaron Cojauny para confirmar la recogida',
      '## Lecciones clave',
      'La comunicación temprana, un único punto de contacto (enlace con el conductor) y ventanas de recogida claras fueron los mayores impulsores del éxito. Los organizadores que prepararon fotos y pines de reunión precisos tuvieron recogidas casi perfectas a tiempo.',
      '## CTA: Realiza tu piloto',
      'Contacta a nuestro equipo para diseñar un piloto para tu organización y obtener una estimación personalizada del ROI.'
    ],
    tags: ['estudio de caso', 'empresa', 'pilotos', 'operaciones'],
    categories: ['operaciones', 'producto'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Equipo Cojauny',
    readingTimeMinutes: 6
  },
  {
    postId: 'post-010',
    slug: 'case-study-corporate-pilot',
    locale: 'fr',
    title: 'Étude de cas : Comment un pilote d’entreprise a réduit les coûts de transfert de 48 %',
    summary: 'Résultats réels du pilote : économies, améliorations du temps et leçons tirées d’un essai corporatif de Cojauny avec une conférence de 120 personnes.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Équipe d’entreprise utilisant Cojauny lors d’un événement',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Étude de cas : Pilote d’entreprise — Conférence de 120 personnes',
      'Nous avons mené un pilote avec une entreprise de taille moyenne participant à une conférence de plusieurs jours. L’objectif : réduire les coûts de transfert et le temps de coordination. Les résultats étaient mesurables et instructifs.',
      '## La configuration',
      'Nous avons créé un espace de travail de voyage, ajouté des vols pour 120 participants et segmenté les transferts par fenêtres d’arrivée. Les organisateurs ont utilisé Cojauny pour proposer des points de rencontre et des capacités par trajet.',
      '## Résultats',
      '- Coût moyen de transfert réduit de 48 %',
      '- Temps moyen de regroupement réduit de 45 min à 12 min',
      '- 92 % des participants ont utilisé Cojauny pour confirmer la prise en charge',
      '## Leçons clés',
      'Une communication précoce, un point de contact unique (liaison avec le chauffeur) et des fenêtres de prise en charge claires ont été les principaux moteurs du succès. Les organisateurs qui ont préparé des photos et des épingles de réunion précises ont eu des prises en charge presque parfaites à l’heure.',
      '## CTA : Réalisez votre pilote',
      'Contactez notre équipe pour concevoir un pilote pour votre organisation et obtenir une estimation personnalisée du ROI.'
    ],
    tags: ['étude de cas', 'entreprise', 'pilotes', 'opérations'],
    categories: ['opérations', 'produit'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Équipe Cojauny',
    readingTimeMinutes: 6
  },
  {
    postId: 'post-010',
    slug: 'case-study-corporate-pilot',
    locale: 'de',
    title: 'Fallstudie: Wie ein Unternehmenspilot die Transferkosten um 48 % senkte',
    summary: 'Echte Pilotenergebnisse: Einsparungen, Zeitverbesserungen und Erkenntnisse aus einem Unternehmensversuch von Cojauny mit einer Konferenz mit 120 Personen.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Unternehmensteam nutzt Cojauny bei einer Veranstaltung',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Fallstudie: Unternehmenspilot — Konferenz mit 120 Personen',
      'Wir haben einen Piloten mit einem mittelständischen Unternehmen durchgeführt, das an einer mehrtägigen Konferenz teilnahm. Ziel war es, die Transferkosten zu senken und die Koordinationszeit zu verkürzen. Die Ergebnisse waren messbar und lehrreich.',
      '## Die Einrichtung',
      'Wir haben einen Reise-Arbeitsbereich erstellt, Flüge für 120 Teilnehmer hinzugefügt und Transfers nach Ankunftsfenstern segmentiert. Die Organisatoren nutzten Cojauny, um Treffpunkte und Kapazitäten pro Fahrt vorzuschlagen.',
      '## Ergebnisse',
      '- Durchschnittliche Transferkosten um 48 % reduziert',
      '- Durchschnittliche Wiedergruppierungszeit von 45 min auf 12 min reduziert',
      '- 92 % der Teilnehmer nutzten Cojauny, um die Abholung zu bestätigen',
      '## Wichtige Erkenntnisse',
      'Frühzeitige Kommunikation, ein einziger Ansprechpartner (Fahrerbindung) und klare Abholfenster waren die größten Erfolgsfaktoren. Organisatoren, die Fotos und präzise Treffpunkt-Pins vorbereiteten, hatten nahezu perfekte pünktliche Abholungen.',
      '## CTA: Führen Sie Ihren Piloten durch',
      'Kontaktieren Sie unser Team, um einen Piloten für Ihre Organisation zu entwerfen und eine maßgeschneiderte ROI-Schätzung zu erhalten.'
    ],
    tags: ['fallstudie', 'unternehmen', 'piloten', 'operationen'],
    categories: ['operationen', 'produkt'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Cojauny Team',
    readingTimeMinutes: 6
  },
  {
    postId: 'post-011',
    slug: 'integrating-flight-data-and-cojauny',
    locale: 'en',
    title: 'Integrating Flight Data with Cojauny: A Guide for Partners and Developers',
    summary: 'Overview for partners on connecting flight APIs and using Cojauny webhooks and SDKs for reliable event updates.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Developer integrating APIs for flight data',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Integrating Flight Data with Cojauny: A Guide for Partners',
      'Reliable flight data is crucial for timely event coordination. This guide explains common integration patterns and practical tips for partners and technical teams.',
      '## Recommended data sources',
      'Use authorized airline/airport feeds (when available) and supplement with global aggregators (e.g., FlightAware, Aerodatabox). Ensure to account for updates like gate changes and cancellations.',
      '## Webhooks and event-based updates',
      'Cojauny supports webhooks to push flight updates to events. Implement retry logic, idempotency keys, and rate limiting. Use event versioning to avoid race conditions during parallel updates.',
      '## SDKs and security',
      'Authenticate integrations using short-lived tokens and rotate keys periodically. For mobile SDKs, keep sensitive logic server-side and use signed requests when necessary.',
      '## CTA: Partner with us',
      'If you are an airline, airport operator, or fleet partner, contact us to explore integration pilot programs and data-sharing agreements.'
    ],
    tags: ['developers', 'api', 'partners', 'flight data'],
    categories: ['documentation', 'product'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Cojauny Engineering Team',
    readingTimeMinutes: 6
  },
  {
    postId: 'post-011',
    slug: 'integrating-flight-data-and-cojauny',
    locale: 'es',
    title: 'Integrar datos de vuelos con Cojauny: Guía para socios y desarrolladores',
    summary: 'Resumen para socios sobre cómo conectar APIs de vuelos y usar webhooks y SDKs de Cojauny para actualizaciones confiables de eventos.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Desarrollador integrando APIs para datos de vuelos',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Integrar datos de vuelos con Cojauny: Guía para socios',
      'Los datos confiables de vuelos son la base de una coordinación oportuna de eventos. Esta guía explica patrones comunes de integración y consejos prácticos para socios y equipos técnicos.',
      '## Fuentes de datos recomendadas',
      'Utiliza fuentes autorizadas de aerolíneas/aeropuertos (cuando estén disponibles) y complementa con agregadores globales (por ejemplo, FlightAware, Aerodatabox). Asegúrate de considerar actualizaciones como cambios de puerta y cancelaciones.',
      '## Webhooks y actualizaciones basadas en eventos',
      'Cojauny admite webhooks para enviar actualizaciones de vuelos a eventos. Implementa lógica de reintento, claves de idempotencia y limitación de tasa. Usa versionado de eventos para evitar condiciones de carrera durante actualizaciones paralelas.',
      '## SDKs y seguridad',
      'Autentica integraciones usando tokens de corta duración y rota claves periódicamente. Para SDKs móviles, mantén la lógica sensible del lado del servidor y usa solicitudes firmadas cuando sea necesario.',
      '## CTA: Asóciate con nosotros',
      'Si eres una aerolínea, operador de aeropuerto o socio de flota, contáctanos para explorar pilotos de integración y acuerdos de intercambio de datos.'
    ],
    tags: ['desarrolladores', 'api', 'socios', 'datos de vuelos'],
    categories: ['documentación', 'producto'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Equipo de Ingeniería Cojauny',
    readingTimeMinutes: 6
  },
  {
    postId: 'post-011',
    slug: 'integrating-flight-data-and-cojauny',
    locale: 'fr',
    title: 'Intégrer des données de vol avec Cojauny : Guide pour partenaires et développeurs',
    summary: 'Aperçu pour les partenaires sur la connexion des API de vol et l’utilisation des webhooks et SDK de Cojauny pour des mises à jour fiables des événements.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Développeur intégrant des API pour des données de vol',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Intégrer des données de vol avec Cojauny : Guide pour partenaires',
      'Des données de vol fiables sont la base d’une coordination ponctuelle des événements. Ce guide explique les modèles d’intégration courants et des conseils pratiques pour les partenaires et les équipes techniques.',
      '## Sources de données recommandées',
      'Utilisez des flux autorisés de compagnies aériennes/aéroports (lorsqu’ils sont disponibles) et complétez avec des agrégateurs mondiaux (par exemple, FlightAware, Aerodatabox). Assurez-vous de prendre en compte les mises à jour telles que les changements de porte et les annulations.',
      '## Webhooks et mises à jour basées sur les événements',
      'Cojauny prend en charge les webhooks pour envoyer des mises à jour de vol aux événements. Implémentez une logique de nouvelle tentative, des clés d’idempotence et une limitation de taux. Utilisez la version des événements pour éviter les conditions de concurrence lors des mises à jour parallèles.',
      '## SDK et sécurité',
      'Authentifiez les intégrations à l’aide de jetons de courte durée et faites pivoter les clés périodiquement. Pour les SDK mobiles, maintenez la logique sensible côté serveur et utilisez des requêtes signées si nécessaire.',
      '## CTA : Devenez partenaire',
      'Si vous êtes une compagnie aérienne, un opérateur d’aéroport ou un partenaire de flotte, contactez-nous pour explorer des pilotes d’intégration et des accords de partage de données.'
    ],
    tags: ['développeurs', 'api', 'partenaires', 'données de vol'],
    categories: ['documentation', 'produit'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Équipe d’ingénierie Cojauny',
    readingTimeMinutes: 6
  },
  {
    postId: 'post-011',
    slug: 'integrating-flight-data-and-cojauny',
    locale: 'de',
    title: 'Integration von Flugdaten mit Cojauny: Leitfaden für Partner und Entwickler',
    summary: 'Überblick für Partner zur Verbindung von Flug-APIs und Nutzung von Cojauny-Webhooks und SDKs für zuverlässige Ereignisaktualisierungen.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Entwickler integriert APIs für Flugdaten',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Integration von Flugdaten mit Cojauny: Partnerleitfaden',
      'Zuverlässige Flugdaten sind das Rückgrat einer rechtzeitigen Ereigniskoordinierung. Dieser Leitfaden erklärt gängige Integrationsmuster und praktische Tipps für Partner und technische Teams.',
      '## Empfohlene Datenquellen',
      'Verwenden Sie autorisierte Airline-/Flughafen-Feeds (sofern verfügbar) und ergänzen Sie diese mit globalen Aggregatoren (z. B. FlightAware, Aerodatabox). Stellen Sie sicher, dass Sie Updates wie Gate-Änderungen und Stornierungen berücksichtigen.',
      '## Webhooks und ereignisgesteuerte Updates',
      'Cojauny unterstützt Webhooks, um Flugaktualisierungen in Ereignisse zu pushen. Implementieren Sie Wiederholungslogik, Idempotenzschlüssel und Ratenbegrenzung. Verwenden Sie Ereignisversionierung, um Rennbedingungen bei parallelen Updates zu vermeiden.',
      '## SDKs und Sicherheit',
      'Authentifizieren Sie Integrationen mit kurzlebigen Token und rotieren Sie Schlüssel regelmäßig. Für mobile SDKs halten Sie sensible Logik serverseitig und verwenden Sie bei Bedarf signierte Anfragen.',
      '## CTA: Werden Sie Partner',
      'Wenn Sie eine Fluggesellschaft, ein Flughafenbetreiber oder ein Flottenpartner sind, kontaktieren Sie uns, um Integrationspiloten und Datenfreigabevereinbarungen zu erkunden.'
    ],
    tags: ['entwickler', 'api', 'partner', 'flugdaten'],
    categories: ['dokumentation', 'produkt'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Cojauny Engineering Team',
    readingTimeMinutes: 6
  },
  {
    postId: 'post-012',
    slug: 'privacy-gdpr-event-chats',
    locale: 'en',
    title: 'Privacy and GDPR: How Cojauny Keeps Event Chats Secure and Compliant',
    summary: 'Overview of Cojauny’s privacy approach: ephemeral chats, data minimization, and user controls to meet GDPR expectations.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Shield icon representing privacy and compliance',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Privacy and GDPR: Event Chat Practices',
      'Privacy is fundamental to Cojauny. We design ephemeral chats, minimal data retention, and clear controls for users to comply with GDPR and reduce risks for both individuals and organizations.',
      '## Ephemeral chat model',
      'Event chats self-destruct 48 hours after the event ends. This means messages, location pings, and attachments are removed from active storage and anonymized in logs when necessary.',
      '## Data minimization and user rights',
      'We only collect what is necessary to coordinate events (flight references, meeting points, limited profile data). Users can request access, rectification, or deletion via support@cojauny.com, and we publish our data processing procedures on the legal page.',
      '## For enterprise customers',
      'We offer Data Processing Agreements (DPAs), regional data residency options, and audit-ready logs for customers requiring compliance evidence.',
      '## CTA: Questions about privacy?',
      'Contact support@cojauny.com for DPA requests or to discuss enterprise compliance needs.'
    ],
    tags: ['privacy', 'gdpr', 'compliance', 'security'],
    categories: ['legal', 'product'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Cojauny Legal Team',
    readingTimeMinutes: 7
  },
  {
    postId: 'post-012',
    slug: 'privacy-gdpr-event-chats',
    locale: 'es',
    title: 'Privacidad y GDPR: Cómo Cojauny mantiene los chats de eventos seguros y conformes',
    summary: 'Resumen del enfoque de privacidad de Cojauny: chats efímeros, minimización de datos y controles de usuario para cumplir con las expectativas de GDPR.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Icono de escudo que representa privacidad y cumplimiento',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Privacidad y GDPR: Prácticas de chats de eventos',
      'La privacidad es fundamental para Cojauny. Diseñamos chats efímeros, retención mínima de datos y controles claros para los usuarios con el fin de cumplir con GDPR y reducir riesgos tanto para individuos como para organizaciones.',
      '## Modelo de chat efímero',
      'Los chats de eventos se autodestruyen 48 horas después de que el evento se cierra. Esto significa que los mensajes, pings de ubicación y archivos adjuntos se eliminan del almacenamiento activo y se anonimizan en los registros cuando es necesario.',
      '## Minimización de datos y derechos de los usuarios',
      'Solo recopilamos lo necesario para coordinar eventos (referencias de vuelos, puntos de encuentro, datos de perfil limitados). Los usuarios pueden solicitar acceso, rectificación o eliminación a través de support@cojauny.com y publicamos nuestros procedimientos de procesamiento de datos en la página legal.',
      '## Para clientes empresariales',
      'Ofrecemos Acuerdos de Procesamiento de Datos (DPAs), opciones de residencia de datos regionales y registros listos para auditorías para clientes que requieren evidencia de cumplimiento.',
      '## CTA: ¿Preguntas sobre privacidad?',
      'Contacta a support@cojauny.com para solicitudes de DPA o para discutir necesidades de cumplimiento empresarial.'
    ],
    tags: ['privacidad', 'gdpr', 'cumplimiento', 'seguridad'],
    categories: ['legal', 'producto'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Equipo Legal Cojauny',
    readingTimeMinutes: 7
  },
  {
    postId: 'post-012',
    slug: 'privacy-gdpr-event-chats',
    locale: 'fr',
    title: 'Confidentialité et RGPD : Comment Cojauny sécurise et conforme les chats d’événements',
    summary: 'Aperçu de l’approche de confidentialité de Cojauny : chats éphémères, minimisation des données et contrôles utilisateur pour répondre aux attentes du RGPD.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Icône de bouclier représentant la confidentialité et la conformité',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Confidentialité et RGPD : Pratiques des chats d’événements',
      'La confidentialité est au cœur de Cojauny. Nous avons conçu des chats éphémères, une rétention minimale des données et des contrôles clairs pour les utilisateurs afin de respecter le RGPD et de réduire les risques pour les individus et les organisations.',
      '## Modèle de chat éphémère',
      'Les chats d’événements s’autodétruisent 48 heures après la clôture de l’événement. Cela signifie que les messages, les pings de localisation et les pièces jointes sont supprimés du stockage actif et anonymisés dans les journaux si nécessaire.',
      '## Minimisation des données et droits des utilisateurs',
      'Nous ne collectons que ce qui est nécessaire pour coordonner les événements (références de vol, points de rencontre, données de profil limitées). Les utilisateurs peuvent demander l’accès, la rectification ou la suppression via support@cojauny.com et nous publions nos procédures de traitement des données sur la page légale.',
      '## Pour les clients d’entreprise',
      'Nous proposons des accords de traitement des données (DPA), des options de résidence des données régionales et des journaux prêts pour les audits pour les clients nécessitant des preuves de conformité.',
      '## CTA : Questions sur la confidentialité ?',
      'Contactez support@cojauny.com pour des demandes de DPA ou pour discuter des besoins de conformité d’entreprise.'
    ],
    tags: ['confidentialité', 'rgpd', 'conformité', 'sécurité'],
    categories: ['juridique', 'produit'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Équipe Juridique Cojauny',
    readingTimeMinutes: 7
  },
  {
    postId: 'post-012',
    slug: 'privacy-gdpr-event-chats',
    locale: 'de',
    title: 'Datenschutz und DSGVO: Wie Cojauny Event-Chats sicher und konform hält',
    summary: 'Überblick über Cojaunys Datenschutzansatz: ephemere Chats, Datenminimierung und Benutzerkontrollen zur Erfüllung der DSGVO-Erwartungen.',
    heroImage: '/images/og-default.svg',
    heroAlt: 'Schildsymbol, das Datenschutz und Compliance darstellt',
    heroWidth: 1280,
    heroHeight: 720,
    body: [
      '# Datenschutz und DSGVO: Praktiken für Event-Chats',
      'Datenschutz ist für Cojauny von zentraler Bedeutung. Wir haben ephemere Chats, minimale Datenspeicherung und klare Benutzerkontrollen entwickelt, um die DSGVO einzuhalten und Risiken für Einzelpersonen und Organisationen zu minimieren.',
      '## Modell für ephemere Chats',
      'Event-Chats zerstören sich 48 Stunden nach Abschluss des Events selbst. Das bedeutet, dass Nachrichten, Standort-Pings und Anhänge aus dem aktiven Speicher entfernt und bei Bedarf in Protokollen anonymisiert werden.',
      '## Datenminimierung und Benutzerrechte',
      'Wir erfassen nur das, was für die Koordination von Events erforderlich ist (Flugreferenzen, Treffpunkte, begrenzte Profildaten). Benutzer können über support@cojauny.com Zugriff, Berichtigung oder Löschung beantragen, und wir veröffentlichen unsere Datenverarbeitungsverfahren auf der Rechtsseite.',
      '## Für Unternehmenskunden',
      'Wir bieten Datenverarbeitungsvereinbarungen (DPA), regionale Datenresidenzoptionen und auditbereite Protokolle für Kunden, die Nachweise zur Einhaltung benötigen.',
      '## CTA: Fragen zum Datenschutz?',
      'Kontaktieren Sie support@cojauny.com für DPA-Anfragen oder um Unternehmensanforderungen zu besprechen.'
    ],
    tags: ['datenschutz', 'dsgvo', 'compliance', 'sicherheit'],
    categories: ['rechtlich', 'produkt'],
    publishedAt: '2025-11-27T10:00:00.000Z',
    updatedAt: '2025-11-27T10:00:00.000Z',
    author: 'Cojauny Rechtsteam',
    readingTimeMinutes: 7
  }
];

/**
 * Filters blog posts by the given locale.
 * @param locale The locale to filter posts by (e.g., 'en', 'es', 'fr', 'de').
 * @returns An array of blog posts matching the locale.
 */
export function getPostsByLocale(locale: Locale): BlogPost[] {
  return blogPosts.filter((post) => post.locale === locale);
}

/**
 * Retrieves a single blog post by locale and slug.
 * @param locale The locale of the post (e.g., 'en', 'es', 'fr', 'de').
 * @param slug The slug of the post.
 * @returns The blog post matching the locale and slug, or undefined if not found.
 */
export function getPost(locale: Locale, slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.locale === locale && post.slug === slug);
}


