import type { Locale } from '@/locales/config';

export interface AirportSeed {
  slug: string;
  iata: string;
  city: string;
  name: string;
}

export const airportSeeds: AirportSeed[] = [
  { slug: 'madrid-barajas', iata: 'MAD', city: 'Madrid', name: 'Adolfo Suárez Madrid-Barajas Airport' },
  { slug: 'barcelona-el-prat', iata: 'BCN', city: 'Barcelona', name: 'Josep Tarradellas Barcelona-El Prat Airport' },
  { slug: 'london-heathrow', iata: 'LHR', city: 'London', name: 'London Heathrow Airport' },
  { slug: 'london-gatwick', iata: 'LGW', city: 'London', name: 'London Gatwick Airport' },
  { slug: 'london-stansted', iata: 'STN', city: 'London', name: 'London Stansted Airport' },
  { slug: 'paris-charles-de-gaulle', iata: 'CDG', city: 'Paris', name: 'Paris Charles de Gaulle Airport' },
  { slug: 'paris-orly', iata: 'ORY', city: 'Paris', name: 'Paris Orly Airport' },
  { slug: 'paris-beauvais', iata: 'BVA', city: 'Paris', name: 'Paris Beauvais Airport' },
  { slug: 'new-york-jfk', iata: 'JFK', city: 'New York', name: 'John F. Kennedy International Airport' },
  { slug: 'new-york-laguardia', iata: 'LGA', city: 'New York', name: 'LaGuardia Airport' },
  { slug: 'new-york-newark', iata: 'EWR', city: 'New York', name: 'Newark Liberty International Airport' },
  { slug: 'frankfurt', iata: 'FRA', city: 'Frankfurt', name: 'Frankfurt Airport' },
  { slug: 'munich', iata: 'MUC', city: 'Munich', name: 'Munich Airport' },
  { slug: 'berlin-brandenburg', iata: 'BER', city: 'Berlin', name: 'Berlin Brandenburg Airport' },
  { slug: 'dusseldorf', iata: 'DUS', city: 'Düsseldorf', name: 'Düsseldorf Airport' },
  { slug: 'hamburg', iata: 'HAM', city: 'Hamburg', name: 'Hamburg Airport' },
  { slug: 'cologne-bonn', iata: 'CGN', city: 'Cologne', name: 'Cologne Bonn Airport' },
  { slug: 'stuttgart', iata: 'STR', city: 'Stuttgart', name: 'Stuttgart Airport' },
  { slug: 'amsterdam-schiphol', iata: 'AMS', city: 'Amsterdam', name: 'Amsterdam Schiphol Airport' },
  { slug: 'rome-fiumicino', iata: 'FCO', city: 'Rome', name: 'Rome Fiumicino Airport' },
  { slug: 'milan-malpensa', iata: 'MXP', city: 'Milan', name: 'Milan Malpensa Airport' },
  { slug: 'milan-linate', iata: 'LIN', city: 'Milan', name: 'Milan Linate Airport' },
  { slug: 'dubai', iata: 'DXB', city: 'Dubai', name: 'Dubai International Airport' },
  { slug: 'doha', iata: 'DOH', city: 'Doha', name: 'Hamad International Airport' },
  { slug: 'abu-dhabi', iata: 'AUH', city: 'Abu Dhabi', name: 'Abu Dhabi International Airport' },
  { slug: 'istanbul', iata: 'IST', city: 'Istanbul', name: 'Istanbul Airport' },
  { slug: 'istanbul-sabiha', iata: 'SAW', city: 'Istanbul', name: 'Istanbul Sabiha Gökçen Airport' },
  { slug: 'vienna', iata: 'VIE', city: 'Vienna', name: 'Vienna International Airport' },
  { slug: 'zurich', iata: 'ZRH', city: 'Zurich', name: 'Zurich Airport' },
  { slug: 'geneva', iata: 'GVA', city: 'Geneva', name: 'Geneva Airport' },
  { slug: 'brussels', iata: 'BRU', city: 'Brussels', name: 'Brussels Airport' },
  { slug: 'lisbon', iata: 'LIS', city: 'Lisbon', name: 'Lisbon Airport' },
  { slug: 'porto', iata: 'OPO', city: 'Porto', name: 'Porto Airport' },
  { slug: 'dublin', iata: 'DUB', city: 'Dublin', name: 'Dublin Airport' },
  { slug: 'manchester', iata: 'MAN', city: 'Manchester', name: 'Manchester Airport' },
  { slug: 'birmingham', iata: 'BHX', city: 'Birmingham', name: 'Birmingham Airport' },
  { slug: 'edinburgh', iata: 'EDI', city: 'Edinburgh', name: 'Edinburgh Airport' },
  { slug: 'glasgow', iata: 'GLA', city: 'Glasgow', name: 'Glasgow Airport' },
  { slug: 'copenhagen', iata: 'CPH', city: 'Copenhagen', name: 'Copenhagen Airport' },
  { slug: 'oslo', iata: 'OSL', city: 'Oslo', name: 'Oslo Airport' },
  { slug: 'stockholm-arlanda', iata: 'ARN', city: 'Stockholm', name: 'Stockholm Arlanda Airport' },
  { slug: 'helsinki', iata: 'HEL', city: 'Helsinki', name: 'Helsinki Airport' },
  { slug: 'warsaw', iata: 'WAW', city: 'Warsaw', name: 'Warsaw Chopin Airport' },
  { slug: 'prague', iata: 'PRG', city: 'Prague', name: 'Václav Havel Airport Prague' },
  { slug: 'budapest', iata: 'BUD', city: 'Budapest', name: 'Budapest Ferenc Liszt Airport' },
  { slug: 'athens', iata: 'ATH', city: 'Athens', name: 'Athens International Airport' },
  { slug: 'tel-aviv', iata: 'TLV', city: 'Tel Aviv', name: 'Ben Gurion Airport' },
  { slug: 'cairo', iata: 'CAI', city: 'Cairo', name: 'Cairo International Airport' },
  { slug: 'johannesburg', iata: 'JNB', city: 'Johannesburg', name: 'O.R. Tambo International Airport' },
  { slug: 'cape-town', iata: 'CPT', city: 'Cape Town', name: 'Cape Town International Airport' },
  { slug: 'nairobi', iata: 'NBO', city: 'Nairobi', name: 'Jomo Kenyatta International Airport' },
  { slug: 'casablanca', iata: 'CMN', city: 'Casablanca', name: 'Mohammed V International Airport' },
  { slug: 'riyadh', iata: 'RUH', city: 'Riyadh', name: 'King Khalid International Airport' },
  { slug: 'jeddah', iata: 'JED', city: 'Jeddah', name: 'King Abdulaziz International Airport' },
  { slug: 'mumbai', iata: 'BOM', city: 'Mumbai', name: 'Chhatrapati Shivaji Maharaj International Airport' },
  { slug: 'delhi', iata: 'DEL', city: 'Delhi', name: 'Indira Gandhi International Airport' },
  { slug: 'bangalore', iata: 'BLR', city: 'Bangalore', name: 'Kempegowda International Airport' },
  { slug: 'hyderabad', iata: 'HYD', city: 'Hyderabad', name: 'Rajiv Gandhi International Airport' },
  { slug: 'chennai', iata: 'MAA', city: 'Chennai', name: 'Chennai International Airport' },
  { slug: 'kolkata', iata: 'CCU', city: 'Kolkata', name: 'Netaji Subhas Chandra Bose International Airport' },
  { slug: 'singapore-changi', iata: 'SIN', city: 'Singapore', name: 'Singapore Changi Airport' },
  { slug: 'kuala-lumpur', iata: 'KUL', city: 'Kuala Lumpur', name: 'Kuala Lumpur International Airport' },
  { slug: 'bangkok-suvarnabhumi', iata: 'BKK', city: 'Bangkok', name: 'Suvarnabhumi Airport' },
  { slug: 'hong-kong', iata: 'HKG', city: 'Hong Kong', name: 'Hong Kong International Airport' },
  { slug: 'shanghai-pudong', iata: 'PVG', city: 'Shanghai', name: 'Shanghai Pudong International Airport' },
  { slug: 'beijing-capital', iata: 'PEK', city: 'Beijing', name: 'Beijing Capital International Airport' },
  { slug: 'guangzhou', iata: 'CAN', city: 'Guangzhou', name: 'Guangzhou Baiyun International Airport' },
  { slug: 'shenzhen', iata: 'SZX', city: 'Shenzhen', name: 'Shenzhen Bao\'an International Airport' },
  { slug: 'seoul-incheon', iata: 'ICN', city: 'Seoul', name: 'Incheon International Airport' },
  { slug: 'tokyo-narita', iata: 'NRT', city: 'Tokyo', name: 'Narita International Airport' },
  { slug: 'tokyo-haneda', iata: 'HND', city: 'Tokyo', name: 'Tokyo Haneda Airport' },
  { slug: 'osaka-kansai', iata: 'KIX', city: 'Osaka', name: 'Kansai International Airport' },
  { slug: 'nagoya', iata: 'NGO', city: 'Nagoya', name: 'Chubu Centrair International Airport' },
  { slug: 'sydney', iata: 'SYD', city: 'Sydney', name: 'Sydney Kingsford Smith Airport' },
  { slug: 'melbourne', iata: 'MEL', city: 'Melbourne', name: 'Melbourne Airport' },
  { slug: 'brisbane', iata: 'BNE', city: 'Brisbane', name: 'Brisbane Airport' },
  { slug: 'perth', iata: 'PER', city: 'Perth', name: 'Perth Airport' },
  { slug: 'auckland', iata: 'AKL', city: 'Auckland', name: 'Auckland Airport' },
  { slug: 'los-angeles', iata: 'LAX', city: 'Los Angeles', name: 'Los Angeles International Airport' },
  { slug: 'san-francisco', iata: 'SFO', city: 'San Francisco', name: 'San Francisco International Airport' },
  { slug: 'san-jose', iata: 'SJC', city: 'San Jose', name: 'San Jose International Airport' },
  { slug: 'oakland', iata: 'OAK', city: 'Oakland', name: 'Oakland International Airport' },
  { slug: 'chicago-ohare', iata: 'ORD', city: 'Chicago', name: 'O\'Hare International Airport' },
  { slug: 'chicago-midway', iata: 'MDW', city: 'Chicago', name: 'Chicago Midway International Airport' },
  { slug: 'dallas-fort-worth', iata: 'DFW', city: 'Dallas', name: 'Dallas Fort Worth International Airport' },
  { slug: 'houston-intercontinental', iata: 'IAH', city: 'Houston', name: 'George Bush Intercontinental Airport' },
  { slug: 'austin', iata: 'AUS', city: 'Austin', name: 'Austin-Bergstrom International Airport' },
  { slug: 'atlanta', iata: 'ATL', city: 'Atlanta', name: 'Hartsfield-Jackson Atlanta International Airport' },
  { slug: 'miami', iata: 'MIA', city: 'Miami', name: 'Miami International Airport' },
  { slug: 'fort-lauderdale', iata: 'FLL', city: 'Fort Lauderdale', name: 'Fort Lauderdale-Hollywood International Airport' },
  { slug: 'orlando', iata: 'MCO', city: 'Orlando', name: 'Orlando International Airport' },
  { slug: 'boston', iata: 'BOS', city: 'Boston', name: 'Boston Logan International Airport' },
  { slug: 'seattle', iata: 'SEA', city: 'Seattle', name: 'Seattle-Tacoma International Airport' },
  { slug: 'portland', iata: 'PDX', city: 'Portland', name: 'Portland International Airport' },
  { slug: 'denver', iata: 'DEN', city: 'Denver', name: 'Denver International Airport' },
  { slug: 'phoenix', iata: 'PHX', city: 'Phoenix', name: 'Phoenix Sky Harbor International Airport' },
  { slug: 'las-vegas', iata: 'LAS', city: 'Las Vegas', name: 'Harry Reid International Airport' },
  { slug: 'toronto-pearson', iata: 'YYZ', city: 'Toronto', name: 'Toronto Pearson International Airport' },
  { slug: 'vancouver', iata: 'YVR', city: 'Vancouver', name: 'Vancouver International Airport' },
  { slug: 'montreal', iata: 'YUL', city: 'Montreal', name: 'Montréal-Trudeau International Airport' },
  { slug: 'mexico-city', iata: 'MEX', city: 'Mexico City', name: 'Mexico City International Airport' },
  { slug: 'guadalajara', iata: 'GDL', city: 'Guadalajara', name: 'Guadalajara International Airport' },
  { slug: 'cancun', iata: 'CUN', city: 'Cancún', name: 'Cancún International Airport' },
  { slug: 'bogota', iata: 'BOG', city: 'Bogotá', name: 'El Dorado International Airport' },
  { slug: 'medellin', iata: 'MDE', city: 'Medellín', name: 'José María Córdova International Airport' },
  { slug: 'lima', iata: 'LIM', city: 'Lima', name: 'Jorge Chávez International Airport' },
  { slug: 'santiago', iata: 'SCL', city: 'Santiago', name: 'Arturo Merino Benítez International Airport' },
  { slug: 'sao-paulo-guarulhos', iata: 'GRU', city: 'São Paulo', name: 'São Paulo/Guarulhos International Airport' },
  { slug: 'rio-galeao', iata: 'GIG', city: 'Rio de Janeiro', name: 'Rio de Janeiro/Galeão International Airport' },
  { slug: 'buenos-aires-ezeiza', iata: 'EZE', city: 'Buenos Aires', name: 'Ministro Pistarini International Airport' },
  { slug: 'panama-city', iata: 'PTY', city: 'Panama City', name: 'Tocumen International Airport' },
  { slug: 'san-jose-costa-rica', iata: 'SJO', city: 'San José', name: 'Juan Santamaría International Airport' },
  { slug: 'valencia', iata: 'VLC', city: 'Valencia', name: 'Valencia Airport' },
  { slug: 'seville', iata: 'SVQ', city: 'Seville', name: 'Seville Airport' },
  { slug: 'malaga', iata: 'AGP', city: 'Málaga', name: 'Málaga-Costa del Sol Airport' },
  { slug: 'palma-de-mallorca', iata: 'PMI', city: 'Palma', name: 'Palma de Mallorca Airport' },
  { slug: 'bilbao', iata: 'BIO', city: 'Bilbao', name: 'Bilbao Airport' },
  { slug: 'nice', iata: 'NCE', city: 'Nice', name: 'Nice Côte d\'Azur Airport' },
  { slug: 'lyon', iata: 'LYS', city: 'Lyon', name: 'Lyon-Saint Exupéry Airport' },
  { slug: 'marseille', iata: 'MRS', city: 'Marseille', name: 'Marseille Provence Airport' },
  { slug: 'toulouse', iata: 'TLS', city: 'Toulouse', name: 'Toulouse-Blagnac Airport' },
  { slug: 'bordeaux', iata: 'BOD', city: 'Bordeaux', name: 'Bordeaux-Mérignac Airport' },
  { slug: 'naples', iata: 'NAP', city: 'Naples', name: 'Naples International Airport' },
  { slug: 'venice', iata: 'VCE', city: 'Venice', name: 'Venice Marco Polo Airport' },
  { slug: 'florence', iata: 'FLR', city: 'Florence', name: 'Florence Airport' },
  { slug: 'krakow', iata: 'KRK', city: 'Kraków', name: 'Kraków John Paul II International Airport' },
  { slug: 'bucharest', iata: 'OTP', city: 'Bucharest', name: 'Henri Coandă International Airport' },
  { slug: 'sofia', iata: 'SOF', city: 'Sofia', name: 'Sofia Airport' },
  { slug: 'zagreb', iata: 'ZAG', city: 'Zagreb', name: 'Zagreb Airport' },
  { slug: 'belgrade', iata: 'BEG', city: 'Belgrade', name: 'Belgrade Nikola Tesla Airport' },
  { slug: 'luxembourg', iata: 'LUX', city: 'Luxembourg', name: 'Luxembourg Airport' },
  { slug: 'reykjavik', iata: 'KEF', city: 'Reykjavík', name: 'Keflavík International Airport' },
  { slug: 'tallinn', iata: 'TLL', city: 'Tallinn', name: 'Tallinn Airport' },
  { slug: 'riga', iata: 'RIX', city: 'Riga', name: 'Riga International Airport' },
  { slug: 'vilnius', iata: 'VNO', city: 'Vilnius', name: 'Vilnius Airport' },
  { slug: 'kiev-boryspil', iata: 'KBP', city: 'Kyiv', name: 'Boryspil International Airport' },
  { slug: 'almaty', iata: 'ALA', city: 'Almaty', name: 'Almaty International Airport' },
  { slug: 'tashkent', iata: 'TAS', city: 'Tashkent', name: 'Tashkent International Airport' },
  { slug: 'baku', iata: 'GYD', city: 'Baku', name: 'Heydar Aliyev International Airport' },
  { slug: 'tbilisi', iata: 'TBS', city: 'Tbilisi', name: 'Tbilisi International Airport' },
  { slug: 'yerevan', iata: 'EVN', city: 'Yerevan', name: 'Zvartnots International Airport' },
  { slug: 'muscat', iata: 'MCT', city: 'Muscat', name: 'Muscat International Airport' },
  { slug: 'kuwait', iata: 'KWI', city: 'Kuwait City', name: 'Kuwait International Airport' },
  { slug: 'bahrain', iata: 'BAH', city: 'Manama', name: 'Bahrain International Airport' },
  { slug: 'amman', iata: 'AMM', city: 'Amman', name: 'Queen Alia International Airport' },
  { slug: 'beirut', iata: 'BEY', city: 'Beirut', name: 'Beirut-Rafic Hariri International Airport' },
  { slug: 'tehran', iata: 'IKA', city: 'Tehran', name: 'Imam Khomeini International Airport' },
  { slug: 'karachi', iata: 'KHI', city: 'Karachi', name: 'Jinnah International Airport' },
  { slug: 'lahore', iata: 'LHE', city: 'Lahore', name: 'Allama Iqbal International Airport' },
  { slug: 'islamabad', iata: 'ISB', city: 'Islamabad', name: 'Islamabad International Airport' },
  { slug: 'colombo', iata: 'CMB', city: 'Colombo', name: 'Bandaranaike International Airport' },
  { slug: 'dhaka', iata: 'DAC', city: 'Dhaka', name: 'Hazrat Shahjalal International Airport' },
  { slug: 'kathmandu', iata: 'KTM', city: 'Kathmandu', name: 'Tribhuvan International Airport' },
  { slug: 'jakarta', iata: 'CGK', city: 'Jakarta', name: 'Soekarno-Hatta International Airport' },
  { slug: 'bali-denpasar', iata: 'DPS', city: 'Denpasar', name: 'Ngurah Rai International Airport' },
  { slug: 'manila', iata: 'MNL', city: 'Manila', name: 'Ninoy Aquino International Airport' },
  { slug: 'cebu', iata: 'CEB', city: 'Cebu', name: 'Mactan-Cebu International Airport' },
  { slug: 'ho-chi-minh', iata: 'SGN', city: 'Ho Chi Minh City', name: 'Tan Son Nhat International Airport' },
  { slug: 'hanoi', iata: 'HAN', city: 'Hanoi', name: 'Noi Bai International Airport' },
  { slug: 'phnom-penh', iata: 'PNH', city: 'Phnom Penh', name: 'Phnom Penh International Airport' },
  { slug: 'taipei', iata: 'TPE', city: 'Taipei', name: 'Taiwan Taoyuan International Airport' },
  { slug: 'macau', iata: 'MFM', city: 'Macau', name: 'Macau International Airport' },
  { slug: 'adelaide', iata: 'ADL', city: 'Adelaide', name: 'Adelaide Airport' },
  { slug: 'christchurch', iata: 'CHC', city: 'Christchurch', name: 'Christchurch Airport' },
  { slug: 'honolulu', iata: 'HNL', city: 'Honolulu', name: 'Daniel K. Inouye International Airport' },
  { slug: 'salt-lake-city', iata: 'SLC', city: 'Salt Lake City', name: 'Salt Lake City International Airport' },
  { slug: 'minneapolis', iata: 'MSP', city: 'Minneapolis', name: 'Minneapolis-Saint Paul International Airport' },
  { slug: 'detroit', iata: 'DTW', city: 'Detroit', name: 'Detroit Metropolitan Airport' },
  { slug: 'philadelphia', iata: 'PHL', city: 'Philadelphia', name: 'Philadelphia International Airport' },
  { slug: 'washington-dulles', iata: 'IAD', city: 'Washington', name: 'Washington Dulles International Airport' },
  { slug: 'washington-reagan', iata: 'DCA', city: 'Washington', name: 'Ronald Reagan Washington National Airport' },
  { slug: 'baltimore', iata: 'BWI', city: 'Baltimore', name: 'Baltimore/Washington International Airport' },
  { slug: 'charlotte', iata: 'CLT', city: 'Charlotte', name: 'Charlotte Douglas International Airport' },
  { slug: 'nashville', iata: 'BNA', city: 'Nashville', name: 'Nashville International Airport' },
  { slug: 'new-orleans', iata: 'MSY', city: 'New Orleans', name: 'Louis Armstrong New Orleans International Airport' },
  { slug: 'san-diego', iata: 'SAN', city: 'San Diego', name: 'San Diego International Airport' },
  { slug: 'sacramento', iata: 'SMF', city: 'Sacramento', name: 'Sacramento International Airport' },
  { slug: 'calgary', iata: 'YYC', city: 'Calgary', name: 'Calgary International Airport' },
  { slug: 'edmonton', iata: 'YEG', city: 'Edmonton', name: 'Edmonton International Airport' },
  { slug: 'ottawa', iata: 'YOW', city: 'Ottawa', name: 'Ottawa Macdonald-Cartier International Airport' },
  { slug: 'montevideo', iata: 'MVD', city: 'Montevideo', name: 'Carrasco International Airport' },
  { slug: 'quito', iata: 'UIO', city: 'Quito', name: 'Mariscal Sucre International Airport' },
  { slug: 'guayaquil', iata: 'GYE', city: 'Guayaquil', name: 'José Joaquín de Olmedo International Airport' },
  { slug: 'caracas', iata: 'CCS', city: 'Caracas', name: 'Simón Bolívar International Airport' },
  { slug: 'havana', iata: 'HAV', city: 'Havana', name: 'José Martí International Airport' },
  { slug: 'punta-cana', iata: 'PUJ', city: 'Punta Cana', name: 'Punta Cana International Airport' },
  { slug: 'santo-domingo', iata: 'SDQ', city: 'Santo Domingo', name: 'Las Américas International Airport' },
  { slug: 'san-juan', iata: 'SJU', city: 'San Juan', name: 'Luis Muñoz Marín International Airport' },
];

export interface Airport {
  slug: string;
  iata: string;
  city: Record<Locale, string>;
  airportName: Record<Locale, string>;
}

const CITY_LOCALES: Partial<Record<string, Partial<Record<Locale, string>>>> = {
  Munich: { de: 'München', fr: 'Munich' },
  Cologne: { de: 'Köln', es: 'Colonia', fr: 'Cologne' },
  Vienna: { de: 'Wien', es: 'Viena', fr: 'Vienne' },
  Zurich: { de: 'Zürich', fr: 'Zurich' },
  Geneva: { fr: 'Genève', de: 'Genf', es: 'Ginebra' },
  Brussels: { fr: 'Bruxelles', de: 'Brüssel', es: 'Bruselas' },
  Lisbon: { es: 'Lisboa', de: 'Lissabon' },
  Copenhagen: { de: 'Kopenhagen', es: 'Copenhague', fr: 'Copenhague' },
  Warsaw: { de: 'Warschau', es: 'Varsovia', fr: 'Varsovie' },
  Prague: { es: 'Praga', fr: 'Prague', de: 'Prag' },
  Budapest: { es: 'Budapest', fr: 'Budapest', de: 'Budapest' },
  Athens: { de: 'Athen', es: 'Atenas', fr: 'Athènes' },
  Moscow: { es: 'Moscú', de: 'Moskau', fr: 'Moscou' },
  Kyiv: { es: 'Kiev', de: 'Kiew', fr: 'Kiev' },
  'Cancún': { en: 'Cancun', de: 'Cancún', fr: 'Cancún' },
  'São Paulo': { en: 'Sao Paulo', es: 'São Paulo', de: 'São Paulo', fr: 'São Paulo' },
  'Buenos Aires': { es: 'Buenos Aires', de: 'Buenos Aires', fr: 'Buenos Aires' },
  'Mexico City': { es: 'Ciudad de México', de: 'Mexiko-Stadt', fr: 'Mexico' },
  'Ho Chi Minh City': { es: 'Ciudad Ho Chi Minh', de: 'Ho-Chi-Minh-Stadt', fr: 'Hô Chi Minh-Ville' },
};

function localizeCity(city: string, locale: Locale): string {
  return CITY_LOCALES[city]?.[locale] ?? city;
}

function seedToAirport(seed: AirportSeed): Airport {
  const locales: Locale[] = ['es', 'en', 'de', 'fr'];
  const city = Object.fromEntries(locales.map((l) => [l, localizeCity(seed.city, l)])) as Record<Locale, string>;
  const airportName = Object.fromEntries(locales.map((l) => [l, seed.name])) as Record<Locale, string>;
  return { slug: seed.slug, iata: seed.iata, city, airportName };
}

export const featuredAirports: Airport[] = airportSeeds.map(seedToAirport);

export function getAirportBySlug(slug: string): Airport | undefined {
  return featuredAirports.find((airport) => airport.slug === slug);
}

export function getAirportByIata(iata: string): Airport | undefined {
  return featuredAirports.find((airport) => airport.iata.toUpperCase() === iata.toUpperCase());
}
